package com.teknei.sitm.gsab.entities;
// Generated 23/06/2015 11:21:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CaupUsuaPref generated by hbm2java
 */
public class CaupUsuaPref  implements java.io.Serializable {


     private int idUsuaPref;
     private CctmCata cctmCataByIdTipoIden;
     private CctmCata cctmCataByIdEsta;
     private CctmCata cctmCataByIdTipo;
     private CctmCata cctmCataByIdTipoIdenPref;
     private CctmPers cctmPers;
     private CoacScre coacScre;
     private String telUsua;
     private String corUsua;
     private Date fchIni;
     private Date fchFin;
     private String usrCrea;
     private Date fchCrea;
     private String usrModi;
     private Date fchModi;
     private String foliRegi;
     private String foliCred;
     private Date fchAfil;
     private String cmnt;
     private String dire;
     private Integer idDire;
     private String persAuto;
     private Set<GsabDocuPers> gsabDocuPerses = new HashSet<GsabDocuPers>(0);
     private Set<CaupAsigTarjPref> caupAsigTarjPrefs = new HashSet<CaupAsigTarjPref>(0);

    public CaupUsuaPref() {
    }

	
    public CaupUsuaPref(int idUsuaPref, CctmCata cctmCataByIdEsta, CctmCata cctmCataByIdTipo, CctmPers cctmPers, CoacScre coacScre, String usrCrea, Date fchCrea) {
        this.idUsuaPref = idUsuaPref;
        this.cctmCataByIdEsta = cctmCataByIdEsta;
        this.cctmCataByIdTipo = cctmCataByIdTipo;
        this.cctmPers = cctmPers;
        this.coacScre = coacScre;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
    }
    public CaupUsuaPref(int idUsuaPref, CctmCata cctmCataByIdTipoIden, CctmCata cctmCataByIdEsta, CctmCata cctmCataByIdTipo, CctmCata cctmCataByIdTipoIdenPref, CctmPers cctmPers, CoacScre coacScre, String telUsua, String corUsua, Date fchIni, Date fchFin, String usrCrea, Date fchCrea, String usrModi, Date fchModi, String foliRegi, String foliCred, Date fchAfil, String cmnt, String dire, Integer idDire, String persAuto, Set<GsabDocuPers> gsabDocuPerses, Set<CaupAsigTarjPref> caupAsigTarjPrefs) {
       this.idUsuaPref = idUsuaPref;
       this.cctmCataByIdTipoIden = cctmCataByIdTipoIden;
       this.cctmCataByIdEsta = cctmCataByIdEsta;
       this.cctmCataByIdTipo = cctmCataByIdTipo;
       this.cctmCataByIdTipoIdenPref = cctmCataByIdTipoIdenPref;
       this.cctmPers = cctmPers;
       this.coacScre = coacScre;
       this.telUsua = telUsua;
       this.corUsua = corUsua;
       this.fchIni = fchIni;
       this.fchFin = fchFin;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.usrModi = usrModi;
       this.fchModi = fchModi;
       this.foliRegi = foliRegi;
       this.foliCred = foliCred;
       this.fchAfil = fchAfil;
       this.cmnt = cmnt;
       this.dire = dire;
       this.idDire = idDire;
       this.persAuto = persAuto;
       this.gsabDocuPerses = gsabDocuPerses;
       this.caupAsigTarjPrefs = caupAsigTarjPrefs;
    }
   
    public int getIdUsuaPref() {
        return this.idUsuaPref;
    }
    
    public void setIdUsuaPref(int idUsuaPref) {
        this.idUsuaPref = idUsuaPref;
    }
    public CctmCata getCctmCataByIdTipoIden() {
        return this.cctmCataByIdTipoIden;
    }
    
    public void setCctmCataByIdTipoIden(CctmCata cctmCataByIdTipoIden) {
        this.cctmCataByIdTipoIden = cctmCataByIdTipoIden;
    }
    public CctmCata getCctmCataByIdEsta() {
        return this.cctmCataByIdEsta;
    }
    
    public void setCctmCataByIdEsta(CctmCata cctmCataByIdEsta) {
        this.cctmCataByIdEsta = cctmCataByIdEsta;
    }
    public CctmCata getCctmCataByIdTipo() {
        return this.cctmCataByIdTipo;
    }
    
    public void setCctmCataByIdTipo(CctmCata cctmCataByIdTipo) {
        this.cctmCataByIdTipo = cctmCataByIdTipo;
    }
    public CctmCata getCctmCataByIdTipoIdenPref() {
        return this.cctmCataByIdTipoIdenPref;
    }
    
    public void setCctmCataByIdTipoIdenPref(CctmCata cctmCataByIdTipoIdenPref) {
        this.cctmCataByIdTipoIdenPref = cctmCataByIdTipoIdenPref;
    }
    public CctmPers getCctmPers() {
        return this.cctmPers;
    }
    
    public void setCctmPers(CctmPers cctmPers) {
        this.cctmPers = cctmPers;
    }
    public CoacScre getCoacScre() {
        return this.coacScre;
    }
    
    public void setCoacScre(CoacScre coacScre) {
        this.coacScre = coacScre;
    }
    public String getTelUsua() {
        return this.telUsua;
    }
    
    public void setTelUsua(String telUsua) {
        this.telUsua = telUsua;
    }
    public String getCorUsua() {
        return this.corUsua;
    }
    
    public void setCorUsua(String corUsua) {
        this.corUsua = corUsua;
    }
    public Date getFchIni() {
        return this.fchIni;
    }
    
    public void setFchIni(Date fchIni) {
        this.fchIni = fchIni;
    }
    public Date getFchFin() {
        return this.fchFin;
    }
    
    public void setFchFin(Date fchFin) {
        this.fchFin = fchFin;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public String getUsrModi() {
        return this.usrModi;
    }
    
    public void setUsrModi(String usrModi) {
        this.usrModi = usrModi;
    }
    public Date getFchModi() {
        return this.fchModi;
    }
    
    public void setFchModi(Date fchModi) {
        this.fchModi = fchModi;
    }
    public String getFoliRegi() {
        return this.foliRegi;
    }
    
    public void setFoliRegi(String foliRegi) {
        this.foliRegi = foliRegi;
    }
    public String getFoliCred() {
        return this.foliCred;
    }
    
    public void setFoliCred(String foliCred) {
        this.foliCred = foliCred;
    }
    public Date getFchAfil() {
        return this.fchAfil;
    }
    
    public void setFchAfil(Date fchAfil) {
        this.fchAfil = fchAfil;
    }
    public String getCmnt() {
        return this.cmnt;
    }
    
    public void setCmnt(String cmnt) {
        this.cmnt = cmnt;
    }
    public String getDire() {
        return this.dire;
    }
    
    public void setDire(String dire) {
        this.dire = dire;
    }
    public Integer getIdDire() {
        return this.idDire;
    }
    
    public void setIdDire(Integer idDire) {
        this.idDire = idDire;
    }
    public String getPersAuto() {
        return this.persAuto;
    }
    
    public void setPersAuto(String persAuto) {
        this.persAuto = persAuto;
    }
    public Set<GsabDocuPers> getGsabDocuPerses() {
        return this.gsabDocuPerses;
    }
    
    public void setGsabDocuPerses(Set<GsabDocuPers> gsabDocuPerses) {
        this.gsabDocuPerses = gsabDocuPerses;
    }
    public Set<CaupAsigTarjPref> getCaupAsigTarjPrefs() {
        return this.caupAsigTarjPrefs;
    }
    
    public void setCaupAsigTarjPrefs(Set<CaupAsigTarjPref> caupAsigTarjPrefs) {
        this.caupAsigTarjPrefs = caupAsigTarjPrefs;
    }




}


