package com.teknei.sitm.gsab.entities;
// Generated 23/06/2015 11:21:34 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CaupUsuaEmpl generated by hbm2java
 */
public class CaupUsuaEmpl  implements java.io.Serializable {


     private int idUsuaEmpl;
     private CctmCata cctmCataByIdEsta;
     private CctmCata cctmCataByIdTipo;
     private CctmEmp cctmEmp;
     private SbopTarj sbopTarj;
     private Date fchIni;
     private Date fchFin;
     private String usrCrea;
     private Date fchCrea;
     private String usrModi;
     private Date fchModi;
     private String conUsuaEmpl;
     private String iniUsuaEmpl;
     private Integer idEqui;

    public CaupUsuaEmpl() {
    }

	
    public CaupUsuaEmpl(int idUsuaEmpl, CctmCata cctmCataByIdEsta, CctmCata cctmCataByIdTipo, CctmEmp cctmEmp, Date fchIni, Date fchFin, String usrCrea, Date fchCrea) {
        this.idUsuaEmpl = idUsuaEmpl;
        this.cctmCataByIdEsta = cctmCataByIdEsta;
        this.cctmCataByIdTipo = cctmCataByIdTipo;
        this.cctmEmp = cctmEmp;
        this.fchIni = fchIni;
        this.fchFin = fchFin;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
    }
    public CaupUsuaEmpl(int idUsuaEmpl, CctmCata cctmCataByIdEsta, CctmCata cctmCataByIdTipo, CctmEmp cctmEmp, SbopTarj sbopTarj, Date fchIni, Date fchFin, String usrCrea, Date fchCrea, String usrModi, Date fchModi, String conUsuaEmpl, String iniUsuaEmpl, Integer idEqui) {
       this.idUsuaEmpl = idUsuaEmpl;
       this.cctmCataByIdEsta = cctmCataByIdEsta;
       this.cctmCataByIdTipo = cctmCataByIdTipo;
       this.cctmEmp = cctmEmp;
       this.sbopTarj = sbopTarj;
       this.fchIni = fchIni;
       this.fchFin = fchFin;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.usrModi = usrModi;
       this.fchModi = fchModi;
       this.conUsuaEmpl = conUsuaEmpl;
       this.iniUsuaEmpl = iniUsuaEmpl;
       this.idEqui = idEqui;
    }
   
    public int getIdUsuaEmpl() {
        return this.idUsuaEmpl;
    }
    
    public void setIdUsuaEmpl(int idUsuaEmpl) {
        this.idUsuaEmpl = idUsuaEmpl;
    }
    public CctmCata getCctmCataByIdEsta() {
        return this.cctmCataByIdEsta;
    }
    
    public void setCctmCataByIdEsta(CctmCata cctmCataByIdEsta) {
        this.cctmCataByIdEsta = cctmCataByIdEsta;
    }
    public CctmCata getCctmCataByIdTipo() {
        return this.cctmCataByIdTipo;
    }
    
    public void setCctmCataByIdTipo(CctmCata cctmCataByIdTipo) {
        this.cctmCataByIdTipo = cctmCataByIdTipo;
    }
    public CctmEmp getCctmEmp() {
        return this.cctmEmp;
    }
    
    public void setCctmEmp(CctmEmp cctmEmp) {
        this.cctmEmp = cctmEmp;
    }
    public SbopTarj getSbopTarj() {
        return this.sbopTarj;
    }
    
    public void setSbopTarj(SbopTarj sbopTarj) {
        this.sbopTarj = sbopTarj;
    }
    public Date getFchIni() {
        return this.fchIni;
    }
    
    public void setFchIni(Date fchIni) {
        this.fchIni = fchIni;
    }
    public Date getFchFin() {
        return this.fchFin;
    }
    
    public void setFchFin(Date fchFin) {
        this.fchFin = fchFin;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public String getUsrModi() {
        return this.usrModi;
    }
    
    public void setUsrModi(String usrModi) {
        this.usrModi = usrModi;
    }
    public Date getFchModi() {
        return this.fchModi;
    }
    
    public void setFchModi(Date fchModi) {
        this.fchModi = fchModi;
    }
    public String getConUsuaEmpl() {
        return this.conUsuaEmpl;
    }
    
    public void setConUsuaEmpl(String conUsuaEmpl) {
        this.conUsuaEmpl = conUsuaEmpl;
    }
    public String getIniUsuaEmpl() {
        return this.iniUsuaEmpl;
    }
    
    public void setIniUsuaEmpl(String iniUsuaEmpl) {
        this.iniUsuaEmpl = iniUsuaEmpl;
    }
    public Integer getIdEqui() {
        return this.idEqui;
    }
    
    public void setIdEqui(Integer idEqui) {
        this.idEqui = idEqui;
    }




}


