package com.teknei.sitm.gsab.entities;
// Generated 23/06/2015 11:21:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CaupCeopConf generated by hbm2java
 */
public class CaupCeopConf  implements java.io.Serializable {


     private int idCeopConf;
     private CaupCeop caupCeop;
     private CctmCata cctmCataByIdTipo;
     private CctmCata cctmCataByIdEsta;
     private CctmProd cctmProd;
     private Integer cantProd;
     private String usrCrea;
     private Date fchCrea;
     private String usrModi;
     private Date fchModi;
     private Set<CaupCeopConfEqui> caupCeopConfEquis = new HashSet<CaupCeopConfEqui>(0);

    public CaupCeopConf() {
    }

	
    public CaupCeopConf(int idCeopConf, CaupCeop caupCeop, CctmCata cctmCataByIdTipo, CctmCata cctmCataByIdEsta, CctmProd cctmProd, String usrCrea, Date fchCrea) {
        this.idCeopConf = idCeopConf;
        this.caupCeop = caupCeop;
        this.cctmCataByIdTipo = cctmCataByIdTipo;
        this.cctmCataByIdEsta = cctmCataByIdEsta;
        this.cctmProd = cctmProd;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
    }
    public CaupCeopConf(int idCeopConf, CaupCeop caupCeop, CctmCata cctmCataByIdTipo, CctmCata cctmCataByIdEsta, CctmProd cctmProd, Integer cantProd, String usrCrea, Date fchCrea, String usrModi, Date fchModi, Set<CaupCeopConfEqui> caupCeopConfEquis) {
       this.idCeopConf = idCeopConf;
       this.caupCeop = caupCeop;
       this.cctmCataByIdTipo = cctmCataByIdTipo;
       this.cctmCataByIdEsta = cctmCataByIdEsta;
       this.cctmProd = cctmProd;
       this.cantProd = cantProd;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.usrModi = usrModi;
       this.fchModi = fchModi;
       this.caupCeopConfEquis = caupCeopConfEquis;
    }
   
    public int getIdCeopConf() {
        return this.idCeopConf;
    }
    
    public void setIdCeopConf(int idCeopConf) {
        this.idCeopConf = idCeopConf;
    }
    public CaupCeop getCaupCeop() {
        return this.caupCeop;
    }
    
    public void setCaupCeop(CaupCeop caupCeop) {
        this.caupCeop = caupCeop;
    }
    public CctmCata getCctmCataByIdTipo() {
        return this.cctmCataByIdTipo;
    }
    
    public void setCctmCataByIdTipo(CctmCata cctmCataByIdTipo) {
        this.cctmCataByIdTipo = cctmCataByIdTipo;
    }
    public CctmCata getCctmCataByIdEsta() {
        return this.cctmCataByIdEsta;
    }
    
    public void setCctmCataByIdEsta(CctmCata cctmCataByIdEsta) {
        this.cctmCataByIdEsta = cctmCataByIdEsta;
    }
    public CctmProd getCctmProd() {
        return this.cctmProd;
    }
    
    public void setCctmProd(CctmProd cctmProd) {
        this.cctmProd = cctmProd;
    }
    public Integer getCantProd() {
        return this.cantProd;
    }
    
    public void setCantProd(Integer cantProd) {
        this.cantProd = cantProd;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public String getUsrModi() {
        return this.usrModi;
    }
    
    public void setUsrModi(String usrModi) {
        this.usrModi = usrModi;
    }
    public Date getFchModi() {
        return this.fchModi;
    }
    
    public void setFchModi(Date fchModi) {
        this.fchModi = fchModi;
    }
    public Set<CaupCeopConfEqui> getCaupCeopConfEquis() {
        return this.caupCeopConfEquis;
    }
    
    public void setCaupCeopConfEquis(Set<CaupCeopConfEqui> caupCeopConfEquis) {
        this.caupCeopConfEquis = caupCeopConfEquis;
    }




}


