package com.teknei.sitm.gsab.entities;
// Generated 23/06/2015 11:21:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CaupCeop generated by hbm2java
 */
public class CaupCeop  implements java.io.Serializable {


     private int idCeop;
     private CctmCata cctmCataByIdTipo;
     private CctmCata cctmCataByIdEsta;
     private CctmEmp cctmEmp;
     private Date fchIni;
     private Date fchFin;
     private String codCeop;
     private String desCeop;
     private String usrCrea;
     private Date fchCrea;
     private String usrModi;
     private Date fchModi;
     private Set<CaupCeopConf> caupCeopConfs = new HashSet<CaupCeopConf>(0);

    public CaupCeop() {
    }

	
    public CaupCeop(int idCeop, CctmCata cctmCataByIdTipo, CctmCata cctmCataByIdEsta, CctmEmp cctmEmp, Date fchIni, String codCeop, String usrCrea, Date fchCrea) {
        this.idCeop = idCeop;
        this.cctmCataByIdTipo = cctmCataByIdTipo;
        this.cctmCataByIdEsta = cctmCataByIdEsta;
        this.cctmEmp = cctmEmp;
        this.fchIni = fchIni;
        this.codCeop = codCeop;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
    }
    public CaupCeop(int idCeop, CctmCata cctmCataByIdTipo, CctmCata cctmCataByIdEsta, CctmEmp cctmEmp, Date fchIni, Date fchFin, String codCeop, String desCeop, String usrCrea, Date fchCrea, String usrModi, Date fchModi, Set<CaupCeopConf> caupCeopConfs) {
       this.idCeop = idCeop;
       this.cctmCataByIdTipo = cctmCataByIdTipo;
       this.cctmCataByIdEsta = cctmCataByIdEsta;
       this.cctmEmp = cctmEmp;
       this.fchIni = fchIni;
       this.fchFin = fchFin;
       this.codCeop = codCeop;
       this.desCeop = desCeop;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.usrModi = usrModi;
       this.fchModi = fchModi;
       this.caupCeopConfs = caupCeopConfs;
    }
   
    public int getIdCeop() {
        return this.idCeop;
    }
    
    public void setIdCeop(int idCeop) {
        this.idCeop = idCeop;
    }
    public CctmCata getCctmCataByIdTipo() {
        return this.cctmCataByIdTipo;
    }
    
    public void setCctmCataByIdTipo(CctmCata cctmCataByIdTipo) {
        this.cctmCataByIdTipo = cctmCataByIdTipo;
    }
    public CctmCata getCctmCataByIdEsta() {
        return this.cctmCataByIdEsta;
    }
    
    public void setCctmCataByIdEsta(CctmCata cctmCataByIdEsta) {
        this.cctmCataByIdEsta = cctmCataByIdEsta;
    }
    public CctmEmp getCctmEmp() {
        return this.cctmEmp;
    }
    
    public void setCctmEmp(CctmEmp cctmEmp) {
        this.cctmEmp = cctmEmp;
    }
    public Date getFchIni() {
        return this.fchIni;
    }
    
    public void setFchIni(Date fchIni) {
        this.fchIni = fchIni;
    }
    public Date getFchFin() {
        return this.fchFin;
    }
    
    public void setFchFin(Date fchFin) {
        this.fchFin = fchFin;
    }
    public String getCodCeop() {
        return this.codCeop;
    }
    
    public void setCodCeop(String codCeop) {
        this.codCeop = codCeop;
    }
    public String getDesCeop() {
        return this.desCeop;
    }
    
    public void setDesCeop(String desCeop) {
        this.desCeop = desCeop;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public String getUsrModi() {
        return this.usrModi;
    }
    
    public void setUsrModi(String usrModi) {
        this.usrModi = usrModi;
    }
    public Date getFchModi() {
        return this.fchModi;
    }
    
    public void setFchModi(Date fchModi) {
        this.fchModi = fchModi;
    }
    public Set<CaupCeopConf> getCaupCeopConfs() {
        return this.caupCeopConfs;
    }
    
    public void setCaupCeopConfs(Set<CaupCeopConf> caupCeopConfs) {
        this.caupCeopConfs = caupCeopConfs;
    }




}


