package com.teknei.sitm.gsab.entities;
// Generated 23/06/2015 11:21:34 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CaupCeopConfEqui generated by hbm2java
 */
public class CaupCeopConfEqui  implements java.io.Serializable {


     private int idCeopConfEqui;
     private CaupCeopConf caupCeopConf;
     private CctmCata cctmCataByIdTipo;
     private CctmCata cctmCataByIdEsta;
     private SbeqEqui sbeqEqui;
     private String usrCrea;
     private Date fchCrea;
     private String usrModi;
     private Date fchModi;

    public CaupCeopConfEqui() {
    }

	
    public CaupCeopConfEqui(int idCeopConfEqui, CaupCeopConf caupCeopConf, CctmCata cctmCataByIdTipo, CctmCata cctmCataByIdEsta, SbeqEqui sbeqEqui, String usrCrea, Date fchCrea) {
        this.idCeopConfEqui = idCeopConfEqui;
        this.caupCeopConf = caupCeopConf;
        this.cctmCataByIdTipo = cctmCataByIdTipo;
        this.cctmCataByIdEsta = cctmCataByIdEsta;
        this.sbeqEqui = sbeqEqui;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
    }
    public CaupCeopConfEqui(int idCeopConfEqui, CaupCeopConf caupCeopConf, CctmCata cctmCataByIdTipo, CctmCata cctmCataByIdEsta, SbeqEqui sbeqEqui, String usrCrea, Date fchCrea, String usrModi, Date fchModi) {
       this.idCeopConfEqui = idCeopConfEqui;
       this.caupCeopConf = caupCeopConf;
       this.cctmCataByIdTipo = cctmCataByIdTipo;
       this.cctmCataByIdEsta = cctmCataByIdEsta;
       this.sbeqEqui = sbeqEqui;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.usrModi = usrModi;
       this.fchModi = fchModi;
    }
   
    public int getIdCeopConfEqui() {
        return this.idCeopConfEqui;
    }
    
    public void setIdCeopConfEqui(int idCeopConfEqui) {
        this.idCeopConfEqui = idCeopConfEqui;
    }
    public CaupCeopConf getCaupCeopConf() {
        return this.caupCeopConf;
    }
    
    public void setCaupCeopConf(CaupCeopConf caupCeopConf) {
        this.caupCeopConf = caupCeopConf;
    }
    public CctmCata getCctmCataByIdTipo() {
        return this.cctmCataByIdTipo;
    }
    
    public void setCctmCataByIdTipo(CctmCata cctmCataByIdTipo) {
        this.cctmCataByIdTipo = cctmCataByIdTipo;
    }
    public CctmCata getCctmCataByIdEsta() {
        return this.cctmCataByIdEsta;
    }
    
    public void setCctmCataByIdEsta(CctmCata cctmCataByIdEsta) {
        this.cctmCataByIdEsta = cctmCataByIdEsta;
    }
    public SbeqEqui getSbeqEqui() {
        return this.sbeqEqui;
    }
    
    public void setSbeqEqui(SbeqEqui sbeqEqui) {
        this.sbeqEqui = sbeqEqui;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public String getUsrModi() {
        return this.usrModi;
    }
    
    public void setUsrModi(String usrModi) {
        this.usrModi = usrModi;
    }
    public Date getFchModi() {
        return this.fchModi;
    }
    
    public void setFchModi(Date fchModi) {
        this.fchModi = fchModi;
    }




}


