package com.teknei.sitm.gsab.entities;
// Generated 23/06/2015 11:21:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CctmColn generated by hbm2java
 */
public class CctmColn  implements java.io.Serializable {


     private CctmColnId id;
     private CctmCata cctmCataByIdEsta;
     private CctmCata cctmCataByIdTipo;
     private String nomColn;
     private String tipoAsen;
     private Integer idCiud;
     private String usrCrea;
     private Date fchCrea;
     private Set<CctmDire> cctmDires = new HashSet<CctmDire>(0);

    public CctmColn() {
    }

	
    public CctmColn(CctmColnId id, CctmCata cctmCataByIdEsta, CctmCata cctmCataByIdTipo, String usrCrea, Date fchCrea) {
        this.id = id;
        this.cctmCataByIdEsta = cctmCataByIdEsta;
        this.cctmCataByIdTipo = cctmCataByIdTipo;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
    }
    public CctmColn(CctmColnId id, CctmCata cctmCataByIdEsta, CctmCata cctmCataByIdTipo, String nomColn, String tipoAsen, Integer idCiud, String usrCrea, Date fchCrea, Set<CctmDire> cctmDires) {
       this.id = id;
       this.cctmCataByIdEsta = cctmCataByIdEsta;
       this.cctmCataByIdTipo = cctmCataByIdTipo;
       this.nomColn = nomColn;
       this.tipoAsen = tipoAsen;
       this.idCiud = idCiud;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.cctmDires = cctmDires;
    }
   
    public CctmColnId getId() {
        return this.id;
    }
    
    public void setId(CctmColnId id) {
        this.id = id;
    }
    public CctmCata getCctmCataByIdEsta() {
        return this.cctmCataByIdEsta;
    }
    
    public void setCctmCataByIdEsta(CctmCata cctmCataByIdEsta) {
        this.cctmCataByIdEsta = cctmCataByIdEsta;
    }
    public CctmCata getCctmCataByIdTipo() {
        return this.cctmCataByIdTipo;
    }
    
    public void setCctmCataByIdTipo(CctmCata cctmCataByIdTipo) {
        this.cctmCataByIdTipo = cctmCataByIdTipo;
    }
    public String getNomColn() {
        return this.nomColn;
    }
    
    public void setNomColn(String nomColn) {
        this.nomColn = nomColn;
    }
    public String getTipoAsen() {
        return this.tipoAsen;
    }
    
    public void setTipoAsen(String tipoAsen) {
        this.tipoAsen = tipoAsen;
    }
    public Integer getIdCiud() {
        return this.idCiud;
    }
    
    public void setIdCiud(Integer idCiud) {
        this.idCiud = idCiud;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public Set<CctmDire> getCctmDires() {
        return this.cctmDires;
    }
    
    public void setCctmDires(Set<CctmDire> cctmDires) {
        this.cctmDires = cctmDires;
    }




}


