package com.teknei.sitm.gsab.entities;
// Generated 23/06/2015 11:21:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CctmCiud generated by hbm2java
 */
public class CctmCiud  implements java.io.Serializable {


     private CctmCiudId id;
     private CctmCata cctmCataByIdEsta;
     private CctmCata cctmCataByIdTipo;
     private String nomCiud;
     private String usrCrea;
     private Date fchCrea;
     private Set<CctmDire> cctmDires = new HashSet<CctmDire>(0);

    public CctmCiud() {
    }

	
    public CctmCiud(CctmCiudId id, CctmCata cctmCataByIdEsta, CctmCata cctmCataByIdTipo, String usrCrea, Date fchCrea) {
        this.id = id;
        this.cctmCataByIdEsta = cctmCataByIdEsta;
        this.cctmCataByIdTipo = cctmCataByIdTipo;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
    }
    public CctmCiud(CctmCiudId id, CctmCata cctmCataByIdEsta, CctmCata cctmCataByIdTipo, String nomCiud, String usrCrea, Date fchCrea, Set<CctmDire> cctmDires) {
       this.id = id;
       this.cctmCataByIdEsta = cctmCataByIdEsta;
       this.cctmCataByIdTipo = cctmCataByIdTipo;
       this.nomCiud = nomCiud;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.cctmDires = cctmDires;
    }
   
    public CctmCiudId getId() {
        return this.id;
    }
    
    public void setId(CctmCiudId id) {
        this.id = id;
    }
    public CctmCata getCctmCataByIdEsta() {
        return this.cctmCataByIdEsta;
    }
    
    public void setCctmCataByIdEsta(CctmCata cctmCataByIdEsta) {
        this.cctmCataByIdEsta = cctmCataByIdEsta;
    }
    public CctmCata getCctmCataByIdTipo() {
        return this.cctmCataByIdTipo;
    }
    
    public void setCctmCataByIdTipo(CctmCata cctmCataByIdTipo) {
        this.cctmCataByIdTipo = cctmCataByIdTipo;
    }
    public String getNomCiud() {
        return this.nomCiud;
    }
    
    public void setNomCiud(String nomCiud) {
        this.nomCiud = nomCiud;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public Set<CctmDire> getCctmDires() {
        return this.cctmDires;
    }
    
    public void setCctmDires(Set<CctmDire> cctmDires) {
        this.cctmDires = cctmDires;
    }




}


