package com.teknei.sitm.gsab.entities;
// Generated 23/06/2015 11:21:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CctmMncp generated by hbm2java
 */
public class CctmMncp  implements java.io.Serializable {


     private CctmMncpId id;
     private CctmCata cctmCataByIdEsta;
     private CctmCata cctmCataByIdTipo;
     private String nomMncp;
     private String usrCrea;
     private Date fchCrea;
     private Set<CctmDire> cctmDires = new HashSet<CctmDire>(0);

    public CctmMncp() {
    }

	
    public CctmMncp(CctmMncpId id, CctmCata cctmCataByIdEsta, CctmCata cctmCataByIdTipo, String usrCrea, Date fchCrea) {
        this.id = id;
        this.cctmCataByIdEsta = cctmCataByIdEsta;
        this.cctmCataByIdTipo = cctmCataByIdTipo;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
    }
    public CctmMncp(CctmMncpId id, CctmCata cctmCataByIdEsta, CctmCata cctmCataByIdTipo, String nomMncp, String usrCrea, Date fchCrea, Set<CctmDire> cctmDires) {
       this.id = id;
       this.cctmCataByIdEsta = cctmCataByIdEsta;
       this.cctmCataByIdTipo = cctmCataByIdTipo;
       this.nomMncp = nomMncp;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.cctmDires = cctmDires;
    }
   
    public CctmMncpId getId() {
        return this.id;
    }
    
    public void setId(CctmMncpId id) {
        this.id = id;
    }
    public CctmCata getCctmCataByIdEsta() {
        return this.cctmCataByIdEsta;
    }
    
    public void setCctmCataByIdEsta(CctmCata cctmCataByIdEsta) {
        this.cctmCataByIdEsta = cctmCataByIdEsta;
    }
    public CctmCata getCctmCataByIdTipo() {
        return this.cctmCataByIdTipo;
    }
    
    public void setCctmCataByIdTipo(CctmCata cctmCataByIdTipo) {
        this.cctmCataByIdTipo = cctmCataByIdTipo;
    }
    public String getNomMncp() {
        return this.nomMncp;
    }
    
    public void setNomMncp(String nomMncp) {
        this.nomMncp = nomMncp;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public Set<CctmDire> getCctmDires() {
        return this.cctmDires;
    }
    
    public void setCctmDires(Set<CctmDire> cctmDires) {
        this.cctmDires = cctmDires;
    }




}


