package com.teknei.sitm.gsab.entities;
// Generated 23/06/2015 11:21:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CctmEmp generated by hbm2java
 */
public class CctmEmp  implements java.io.Serializable {


     private int idEmp;
     private CctmCata cctmCataByIdLgarTrab;
     private CctmCata cctmCataByIdTipo;
     private CctmCata cctmCataByIdEsta;
     private CctmPers cctmPers;
     private String noEmp;
     private Date fchOpeAlta;
     private Date fchOpeBaja;
     private String motBaja;
     private String cmnt;
     private String usrCrea;
     private Date fchCrea;
     private String usrModi;
     private Date fchModi;
     private Set<CaupCeop> caupCeops = new HashSet<CaupCeop>(0);
     private Set<CaupUsuaEmpl> caupUsuaEmpls = new HashSet<CaupUsuaEmpl>(0);
     private Set<GsabDocuPers> gsabDocuPerses = new HashSet<GsabDocuPers>(0);

    public CctmEmp() {
    }

	
    public CctmEmp(int idEmp, CctmCata cctmCataByIdLgarTrab, CctmCata cctmCataByIdEsta, CctmPers cctmPers, Date fchOpeAlta, String usrCrea, Date fchCrea) {
        this.idEmp = idEmp;
        this.cctmCataByIdLgarTrab = cctmCataByIdLgarTrab;
        this.cctmCataByIdEsta = cctmCataByIdEsta;
        this.cctmPers = cctmPers;
        this.fchOpeAlta = fchOpeAlta;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
    }
    public CctmEmp(int idEmp, CctmCata cctmCataByIdLgarTrab, CctmCata cctmCataByIdTipo, CctmCata cctmCataByIdEsta, CctmPers cctmPers, String noEmp, Date fchOpeAlta, Date fchOpeBaja, String motBaja, String cmnt, String usrCrea, Date fchCrea, String usrModi, Date fchModi, Set<CaupCeop> caupCeops, Set<CaupUsuaEmpl> caupUsuaEmpls, Set<GsabDocuPers> gsabDocuPerses) {
       this.idEmp = idEmp;
       this.cctmCataByIdLgarTrab = cctmCataByIdLgarTrab;
       this.cctmCataByIdTipo = cctmCataByIdTipo;
       this.cctmCataByIdEsta = cctmCataByIdEsta;
       this.cctmPers = cctmPers;
       this.noEmp = noEmp;
       this.fchOpeAlta = fchOpeAlta;
       this.fchOpeBaja = fchOpeBaja;
       this.motBaja = motBaja;
       this.cmnt = cmnt;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.usrModi = usrModi;
       this.fchModi = fchModi;
       this.caupCeops = caupCeops;
       this.caupUsuaEmpls = caupUsuaEmpls;
       this.gsabDocuPerses = gsabDocuPerses;
    }
   
    public int getIdEmp() {
        return this.idEmp;
    }
    
    public void setIdEmp(int idEmp) {
        this.idEmp = idEmp;
    }
    public CctmCata getCctmCataByIdLgarTrab() {
        return this.cctmCataByIdLgarTrab;
    }
    
    public void setCctmCataByIdLgarTrab(CctmCata cctmCataByIdLgarTrab) {
        this.cctmCataByIdLgarTrab = cctmCataByIdLgarTrab;
    }
    public CctmCata getCctmCataByIdTipo() {
        return this.cctmCataByIdTipo;
    }
    
    public void setCctmCataByIdTipo(CctmCata cctmCataByIdTipo) {
        this.cctmCataByIdTipo = cctmCataByIdTipo;
    }
    public CctmCata getCctmCataByIdEsta() {
        return this.cctmCataByIdEsta;
    }
    
    public void setCctmCataByIdEsta(CctmCata cctmCataByIdEsta) {
        this.cctmCataByIdEsta = cctmCataByIdEsta;
    }
    public CctmPers getCctmPers() {
        return this.cctmPers;
    }
    
    public void setCctmPers(CctmPers cctmPers) {
        this.cctmPers = cctmPers;
    }
    public String getNoEmp() {
        return this.noEmp;
    }
    
    public void setNoEmp(String noEmp) {
        this.noEmp = noEmp;
    }
    public Date getFchOpeAlta() {
        return this.fchOpeAlta;
    }
    
    public void setFchOpeAlta(Date fchOpeAlta) {
        this.fchOpeAlta = fchOpeAlta;
    }
    public Date getFchOpeBaja() {
        return this.fchOpeBaja;
    }
    
    public void setFchOpeBaja(Date fchOpeBaja) {
        this.fchOpeBaja = fchOpeBaja;
    }
    public String getMotBaja() {
        return this.motBaja;
    }
    
    public void setMotBaja(String motBaja) {
        this.motBaja = motBaja;
    }
    public String getCmnt() {
        return this.cmnt;
    }
    
    public void setCmnt(String cmnt) {
        this.cmnt = cmnt;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public String getUsrModi() {
        return this.usrModi;
    }
    
    public void setUsrModi(String usrModi) {
        this.usrModi = usrModi;
    }
    public Date getFchModi() {
        return this.fchModi;
    }
    
    public void setFchModi(Date fchModi) {
        this.fchModi = fchModi;
    }
    public Set<CaupCeop> getCaupCeops() {
        return this.caupCeops;
    }
    
    public void setCaupCeops(Set<CaupCeop> caupCeops) {
        this.caupCeops = caupCeops;
    }
    public Set<CaupUsuaEmpl> getCaupUsuaEmpls() {
        return this.caupUsuaEmpls;
    }
    
    public void setCaupUsuaEmpls(Set<CaupUsuaEmpl> caupUsuaEmpls) {
        this.caupUsuaEmpls = caupUsuaEmpls;
    }
    public Set<GsabDocuPers> getGsabDocuPerses() {
        return this.gsabDocuPerses;
    }
    
    public void setGsabDocuPerses(Set<GsabDocuPers> gsabDocuPerses) {
        this.gsabDocuPerses = gsabDocuPerses;
    }




}


