package com.teknei.sitm.gsab.entities;
// Generated 23/06/2015 11:21:34 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CctmProd generated by hbm2java
 */
public class CctmProd  implements java.io.Serializable {


     private int idProd;
     private String codProd;
     private String desProd;
     private String usrCrea;
     private Date fchCrea;
     private String usrModi;
     private Date fchModi;
     private Integer idGpro;
     private Integer idProa;
     private int idUmed;
     private Integer idUmep;
     private String dimProd;
     private String matProd;
     private String din;
     private BigDecimal pesoNeto;
     private BigDecimal pesoBrut;
     private Integer idUpes;
     private BigDecimal volTot;
     private Integer idUvol;
     private String conAlma;
     private String indTemp;
     private Integer idSect;
     private Short idCeti;
     private Integer idFeti;
     private Character inac;
     private String ean;
     private BigDecimal dimLong;
     private BigDecimal dimAnch;
     private BigDecimal dimAltu;
     private Integer idUlaa;
     private Date fchIniVal;
     private Date fchLiq;
     private Integer idCpro;
     private Integer idCfis;
     private String numPiez;
     private String numFabr;
     private String indVisc;
     private Integer idPais;
     private Character prec;
     private Integer idMarc;
     private String codBarr;
     private Integer idMedi;
     private int idEsta;
     private int idTipo;
     private Integer cantAlmaMini;
     private Integer cantAlmaMaxi;
     private Integer tiemAlmaMini;
     private Integer tiemAlmaMaxi;
     private Integer tiemCadu;
     private BigDecimal precAnteCont;
     private BigDecimal precActuCont;
     private Integer stocTotaCont;
     private BigDecimal valoTotaCont;
     private Integer idConSis;
     private Set<CaupCeopConf> caupCeopConfs = new HashSet<CaupCeopConf>(0);

    public CctmProd() {
    }

	
    public CctmProd(int idProd, String codProd, String desProd, String usrCrea, Date fchCrea, int idUmed, int idEsta, int idTipo) {
        this.idProd = idProd;
        this.codProd = codProd;
        this.desProd = desProd;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
        this.idUmed = idUmed;
        this.idEsta = idEsta;
        this.idTipo = idTipo;
    }
    public CctmProd(int idProd, String codProd, String desProd, String usrCrea, Date fchCrea, String usrModi, Date fchModi, Integer idGpro, Integer idProa, int idUmed, Integer idUmep, String dimProd, String matProd, String din, BigDecimal pesoNeto, BigDecimal pesoBrut, Integer idUpes, BigDecimal volTot, Integer idUvol, String conAlma, String indTemp, Integer idSect, Short idCeti, Integer idFeti, Character inac, String ean, BigDecimal dimLong, BigDecimal dimAnch, BigDecimal dimAltu, Integer idUlaa, Date fchIniVal, Date fchLiq, Integer idCpro, Integer idCfis, String numPiez, String numFabr, String indVisc, Integer idPais, Character prec, Integer idMarc, String codBarr, Integer idMedi, int idEsta, int idTipo, Integer cantAlmaMini, Integer cantAlmaMaxi, Integer tiemAlmaMini, Integer tiemAlmaMaxi, Integer tiemCadu, BigDecimal precAnteCont, BigDecimal precActuCont, Integer stocTotaCont, BigDecimal valoTotaCont, Integer idConSis, Set<CaupCeopConf> caupCeopConfs) {
       this.idProd = idProd;
       this.codProd = codProd;
       this.desProd = desProd;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.usrModi = usrModi;
       this.fchModi = fchModi;
       this.idGpro = idGpro;
       this.idProa = idProa;
       this.idUmed = idUmed;
       this.idUmep = idUmep;
       this.dimProd = dimProd;
       this.matProd = matProd;
       this.din = din;
       this.pesoNeto = pesoNeto;
       this.pesoBrut = pesoBrut;
       this.idUpes = idUpes;
       this.volTot = volTot;
       this.idUvol = idUvol;
       this.conAlma = conAlma;
       this.indTemp = indTemp;
       this.idSect = idSect;
       this.idCeti = idCeti;
       this.idFeti = idFeti;
       this.inac = inac;
       this.ean = ean;
       this.dimLong = dimLong;
       this.dimAnch = dimAnch;
       this.dimAltu = dimAltu;
       this.idUlaa = idUlaa;
       this.fchIniVal = fchIniVal;
       this.fchLiq = fchLiq;
       this.idCpro = idCpro;
       this.idCfis = idCfis;
       this.numPiez = numPiez;
       this.numFabr = numFabr;
       this.indVisc = indVisc;
       this.idPais = idPais;
       this.prec = prec;
       this.idMarc = idMarc;
       this.codBarr = codBarr;
       this.idMedi = idMedi;
       this.idEsta = idEsta;
       this.idTipo = idTipo;
       this.cantAlmaMini = cantAlmaMini;
       this.cantAlmaMaxi = cantAlmaMaxi;
       this.tiemAlmaMini = tiemAlmaMini;
       this.tiemAlmaMaxi = tiemAlmaMaxi;
       this.tiemCadu = tiemCadu;
       this.precAnteCont = precAnteCont;
       this.precActuCont = precActuCont;
       this.stocTotaCont = stocTotaCont;
       this.valoTotaCont = valoTotaCont;
       this.idConSis = idConSis;
       this.caupCeopConfs = caupCeopConfs;
    }
   
    public int getIdProd() {
        return this.idProd;
    }
    
    public void setIdProd(int idProd) {
        this.idProd = idProd;
    }
    public String getCodProd() {
        return this.codProd;
    }
    
    public void setCodProd(String codProd) {
        this.codProd = codProd;
    }
    public String getDesProd() {
        return this.desProd;
    }
    
    public void setDesProd(String desProd) {
        this.desProd = desProd;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public String getUsrModi() {
        return this.usrModi;
    }
    
    public void setUsrModi(String usrModi) {
        this.usrModi = usrModi;
    }
    public Date getFchModi() {
        return this.fchModi;
    }
    
    public void setFchModi(Date fchModi) {
        this.fchModi = fchModi;
    }
    public Integer getIdGpro() {
        return this.idGpro;
    }
    
    public void setIdGpro(Integer idGpro) {
        this.idGpro = idGpro;
    }
    public Integer getIdProa() {
        return this.idProa;
    }
    
    public void setIdProa(Integer idProa) {
        this.idProa = idProa;
    }
    public int getIdUmed() {
        return this.idUmed;
    }
    
    public void setIdUmed(int idUmed) {
        this.idUmed = idUmed;
    }
    public Integer getIdUmep() {
        return this.idUmep;
    }
    
    public void setIdUmep(Integer idUmep) {
        this.idUmep = idUmep;
    }
    public String getDimProd() {
        return this.dimProd;
    }
    
    public void setDimProd(String dimProd) {
        this.dimProd = dimProd;
    }
    public String getMatProd() {
        return this.matProd;
    }
    
    public void setMatProd(String matProd) {
        this.matProd = matProd;
    }
    public String getDin() {
        return this.din;
    }
    
    public void setDin(String din) {
        this.din = din;
    }
    public BigDecimal getPesoNeto() {
        return this.pesoNeto;
    }
    
    public void setPesoNeto(BigDecimal pesoNeto) {
        this.pesoNeto = pesoNeto;
    }
    public BigDecimal getPesoBrut() {
        return this.pesoBrut;
    }
    
    public void setPesoBrut(BigDecimal pesoBrut) {
        this.pesoBrut = pesoBrut;
    }
    public Integer getIdUpes() {
        return this.idUpes;
    }
    
    public void setIdUpes(Integer idUpes) {
        this.idUpes = idUpes;
    }
    public BigDecimal getVolTot() {
        return this.volTot;
    }
    
    public void setVolTot(BigDecimal volTot) {
        this.volTot = volTot;
    }
    public Integer getIdUvol() {
        return this.idUvol;
    }
    
    public void setIdUvol(Integer idUvol) {
        this.idUvol = idUvol;
    }
    public String getConAlma() {
        return this.conAlma;
    }
    
    public void setConAlma(String conAlma) {
        this.conAlma = conAlma;
    }
    public String getIndTemp() {
        return this.indTemp;
    }
    
    public void setIndTemp(String indTemp) {
        this.indTemp = indTemp;
    }
    public Integer getIdSect() {
        return this.idSect;
    }
    
    public void setIdSect(Integer idSect) {
        this.idSect = idSect;
    }
    public Short getIdCeti() {
        return this.idCeti;
    }
    
    public void setIdCeti(Short idCeti) {
        this.idCeti = idCeti;
    }
    public Integer getIdFeti() {
        return this.idFeti;
    }
    
    public void setIdFeti(Integer idFeti) {
        this.idFeti = idFeti;
    }
    public Character getInac() {
        return this.inac;
    }
    
    public void setInac(Character inac) {
        this.inac = inac;
    }
    public String getEan() {
        return this.ean;
    }
    
    public void setEan(String ean) {
        this.ean = ean;
    }
    public BigDecimal getDimLong() {
        return this.dimLong;
    }
    
    public void setDimLong(BigDecimal dimLong) {
        this.dimLong = dimLong;
    }
    public BigDecimal getDimAnch() {
        return this.dimAnch;
    }
    
    public void setDimAnch(BigDecimal dimAnch) {
        this.dimAnch = dimAnch;
    }
    public BigDecimal getDimAltu() {
        return this.dimAltu;
    }
    
    public void setDimAltu(BigDecimal dimAltu) {
        this.dimAltu = dimAltu;
    }
    public Integer getIdUlaa() {
        return this.idUlaa;
    }
    
    public void setIdUlaa(Integer idUlaa) {
        this.idUlaa = idUlaa;
    }
    public Date getFchIniVal() {
        return this.fchIniVal;
    }
    
    public void setFchIniVal(Date fchIniVal) {
        this.fchIniVal = fchIniVal;
    }
    public Date getFchLiq() {
        return this.fchLiq;
    }
    
    public void setFchLiq(Date fchLiq) {
        this.fchLiq = fchLiq;
    }
    public Integer getIdCpro() {
        return this.idCpro;
    }
    
    public void setIdCpro(Integer idCpro) {
        this.idCpro = idCpro;
    }
    public Integer getIdCfis() {
        return this.idCfis;
    }
    
    public void setIdCfis(Integer idCfis) {
        this.idCfis = idCfis;
    }
    public String getNumPiez() {
        return this.numPiez;
    }
    
    public void setNumPiez(String numPiez) {
        this.numPiez = numPiez;
    }
    public String getNumFabr() {
        return this.numFabr;
    }
    
    public void setNumFabr(String numFabr) {
        this.numFabr = numFabr;
    }
    public String getIndVisc() {
        return this.indVisc;
    }
    
    public void setIndVisc(String indVisc) {
        this.indVisc = indVisc;
    }
    public Integer getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(Integer idPais) {
        this.idPais = idPais;
    }
    public Character getPrec() {
        return this.prec;
    }
    
    public void setPrec(Character prec) {
        this.prec = prec;
    }
    public Integer getIdMarc() {
        return this.idMarc;
    }
    
    public void setIdMarc(Integer idMarc) {
        this.idMarc = idMarc;
    }
    public String getCodBarr() {
        return this.codBarr;
    }
    
    public void setCodBarr(String codBarr) {
        this.codBarr = codBarr;
    }
    public Integer getIdMedi() {
        return this.idMedi;
    }
    
    public void setIdMedi(Integer idMedi) {
        this.idMedi = idMedi;
    }
    public int getIdEsta() {
        return this.idEsta;
    }
    
    public void setIdEsta(int idEsta) {
        this.idEsta = idEsta;
    }
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }
    public Integer getCantAlmaMini() {
        return this.cantAlmaMini;
    }
    
    public void setCantAlmaMini(Integer cantAlmaMini) {
        this.cantAlmaMini = cantAlmaMini;
    }
    public Integer getCantAlmaMaxi() {
        return this.cantAlmaMaxi;
    }
    
    public void setCantAlmaMaxi(Integer cantAlmaMaxi) {
        this.cantAlmaMaxi = cantAlmaMaxi;
    }
    public Integer getTiemAlmaMini() {
        return this.tiemAlmaMini;
    }
    
    public void setTiemAlmaMini(Integer tiemAlmaMini) {
        this.tiemAlmaMini = tiemAlmaMini;
    }
    public Integer getTiemAlmaMaxi() {
        return this.tiemAlmaMaxi;
    }
    
    public void setTiemAlmaMaxi(Integer tiemAlmaMaxi) {
        this.tiemAlmaMaxi = tiemAlmaMaxi;
    }
    public Integer getTiemCadu() {
        return this.tiemCadu;
    }
    
    public void setTiemCadu(Integer tiemCadu) {
        this.tiemCadu = tiemCadu;
    }
    public BigDecimal getPrecAnteCont() {
        return this.precAnteCont;
    }
    
    public void setPrecAnteCont(BigDecimal precAnteCont) {
        this.precAnteCont = precAnteCont;
    }
    public BigDecimal getPrecActuCont() {
        return this.precActuCont;
    }
    
    public void setPrecActuCont(BigDecimal precActuCont) {
        this.precActuCont = precActuCont;
    }
    public Integer getStocTotaCont() {
        return this.stocTotaCont;
    }
    
    public void setStocTotaCont(Integer stocTotaCont) {
        this.stocTotaCont = stocTotaCont;
    }
    public BigDecimal getValoTotaCont() {
        return this.valoTotaCont;
    }
    
    public void setValoTotaCont(BigDecimal valoTotaCont) {
        this.valoTotaCont = valoTotaCont;
    }
    public Integer getIdConSis() {
        return this.idConSis;
    }
    
    public void setIdConSis(Integer idConSis) {
        this.idConSis = idConSis;
    }
    public Set<CaupCeopConf> getCaupCeopConfs() {
        return this.caupCeopConfs;
    }
    
    public void setCaupCeopConfs(Set<CaupCeopConf> caupCeopConfs) {
        this.caupCeopConfs = caupCeopConfs;
    }




}


