package com.teknei.sitm.gsab.entities;
// Generated 23/06/2015 11:21:34 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CctmDire generated by hbm2java
 */
public class CctmDire  implements java.io.Serializable {


     private int idDire;
     private CctmCata cctmCataByIdTipo;
     private CctmCata cctmCataByIdEsta;
     private CctmCiud cctmCiud;
     private CctmCodp cctmCodp;
     private CctmColn cctmColn;
     private CctmEstd cctmEstd;
     private CctmMncp cctmMncp;
     private Double latDire;
     private Double lonDire;
     private String callDire;
     private String nintDire;
     private String nextDire;
     private Integer idTipoUbi;
     private String usrCrea;
     private Date fchCrea;
     private String usrModi;
     private Date fchModi;

    public CctmDire() {
    }

	
    public CctmDire(int idDire, CctmCata cctmCataByIdTipo, CctmCata cctmCataByIdEsta, String usrCrea, Date fchCrea) {
        this.idDire = idDire;
        this.cctmCataByIdTipo = cctmCataByIdTipo;
        this.cctmCataByIdEsta = cctmCataByIdEsta;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
    }
    public CctmDire(int idDire, CctmCata cctmCataByIdTipo, CctmCata cctmCataByIdEsta, CctmCiud cctmCiud, CctmCodp cctmCodp, CctmColn cctmColn, CctmEstd cctmEstd, CctmMncp cctmMncp, Double latDire, Double lonDire, String callDire, String nintDire, String nextDire, Integer idTipoUbi, String usrCrea, Date fchCrea, String usrModi, Date fchModi) {
       this.idDire = idDire;
       this.cctmCataByIdTipo = cctmCataByIdTipo;
       this.cctmCataByIdEsta = cctmCataByIdEsta;
       this.cctmCiud = cctmCiud;
       this.cctmCodp = cctmCodp;
       this.cctmColn = cctmColn;
       this.cctmEstd = cctmEstd;
       this.cctmMncp = cctmMncp;
       this.latDire = latDire;
       this.lonDire = lonDire;
       this.callDire = callDire;
       this.nintDire = nintDire;
       this.nextDire = nextDire;
       this.idTipoUbi = idTipoUbi;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.usrModi = usrModi;
       this.fchModi = fchModi;
    }
   
    public int getIdDire() {
        return this.idDire;
    }
    
    public void setIdDire(int idDire) {
        this.idDire = idDire;
    }
    public CctmCata getCctmCataByIdTipo() {
        return this.cctmCataByIdTipo;
    }
    
    public void setCctmCataByIdTipo(CctmCata cctmCataByIdTipo) {
        this.cctmCataByIdTipo = cctmCataByIdTipo;
    }
    public CctmCata getCctmCataByIdEsta() {
        return this.cctmCataByIdEsta;
    }
    
    public void setCctmCataByIdEsta(CctmCata cctmCataByIdEsta) {
        this.cctmCataByIdEsta = cctmCataByIdEsta;
    }
    public CctmCiud getCctmCiud() {
        return this.cctmCiud;
    }
    
    public void setCctmCiud(CctmCiud cctmCiud) {
        this.cctmCiud = cctmCiud;
    }
    public CctmCodp getCctmCodp() {
        return this.cctmCodp;
    }
    
    public void setCctmCodp(CctmCodp cctmCodp) {
        this.cctmCodp = cctmCodp;
    }
    public CctmColn getCctmColn() {
        return this.cctmColn;
    }
    
    public void setCctmColn(CctmColn cctmColn) {
        this.cctmColn = cctmColn;
    }
    public CctmEstd getCctmEstd() {
        return this.cctmEstd;
    }
    
    public void setCctmEstd(CctmEstd cctmEstd) {
        this.cctmEstd = cctmEstd;
    }
    public CctmMncp getCctmMncp() {
        return this.cctmMncp;
    }
    
    public void setCctmMncp(CctmMncp cctmMncp) {
        this.cctmMncp = cctmMncp;
    }
    public Double getLatDire() {
        return this.latDire;
    }
    
    public void setLatDire(Double latDire) {
        this.latDire = latDire;
    }
    public Double getLonDire() {
        return this.lonDire;
    }
    
    public void setLonDire(Double lonDire) {
        this.lonDire = lonDire;
    }
    public String getCallDire() {
        return this.callDire;
    }
    
    public void setCallDire(String callDire) {
        this.callDire = callDire;
    }
    public String getNintDire() {
        return this.nintDire;
    }
    
    public void setNintDire(String nintDire) {
        this.nintDire = nintDire;
    }
    public String getNextDire() {
        return this.nextDire;
    }
    
    public void setNextDire(String nextDire) {
        this.nextDire = nextDire;
    }
    public Integer getIdTipoUbi() {
        return this.idTipoUbi;
    }
    
    public void setIdTipoUbi(Integer idTipoUbi) {
        this.idTipoUbi = idTipoUbi;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public String getUsrModi() {
        return this.usrModi;
    }
    
    public void setUsrModi(String usrModi) {
        this.usrModi = usrModi;
    }
    public Date getFchModi() {
        return this.fchModi;
    }
    
    public void setFchModi(Date fchModi) {
        this.fchModi = fchModi;
    }




}


