package com.teknei.sitm.gsab.entities;
// Generated 23/06/2015 11:21:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CctmEstd generated by hbm2java
 */
public class CctmEstd  implements java.io.Serializable {


     private int idEstd;
     private CctmCata cctmCataByIdTipo;
     private CctmCata cctmCataByIdEsta;
     private String nomEstd;
     private String usrCrea;
     private Date fchCrea;
     private Set<CctmDire> cctmDires = new HashSet<CctmDire>(0);

    public CctmEstd() {
    }

	
    public CctmEstd(int idEstd, CctmCata cctmCataByIdTipo, CctmCata cctmCataByIdEsta, String usrCrea, Date fchCrea) {
        this.idEstd = idEstd;
        this.cctmCataByIdTipo = cctmCataByIdTipo;
        this.cctmCataByIdEsta = cctmCataByIdEsta;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
    }
    public CctmEstd(int idEstd, CctmCata cctmCataByIdTipo, CctmCata cctmCataByIdEsta, String nomEstd, String usrCrea, Date fchCrea, Set<CctmDire> cctmDires) {
       this.idEstd = idEstd;
       this.cctmCataByIdTipo = cctmCataByIdTipo;
       this.cctmCataByIdEsta = cctmCataByIdEsta;
       this.nomEstd = nomEstd;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.cctmDires = cctmDires;
    }
   
    public int getIdEstd() {
        return this.idEstd;
    }
    
    public void setIdEstd(int idEstd) {
        this.idEstd = idEstd;
    }
    public CctmCata getCctmCataByIdTipo() {
        return this.cctmCataByIdTipo;
    }
    
    public void setCctmCataByIdTipo(CctmCata cctmCataByIdTipo) {
        this.cctmCataByIdTipo = cctmCataByIdTipo;
    }
    public CctmCata getCctmCataByIdEsta() {
        return this.cctmCataByIdEsta;
    }
    
    public void setCctmCataByIdEsta(CctmCata cctmCataByIdEsta) {
        this.cctmCataByIdEsta = cctmCataByIdEsta;
    }
    public String getNomEstd() {
        return this.nomEstd;
    }
    
    public void setNomEstd(String nomEstd) {
        this.nomEstd = nomEstd;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public Set<CctmDire> getCctmDires() {
        return this.cctmDires;
    }
    
    public void setCctmDires(Set<CctmDire> cctmDires) {
        this.cctmDires = cctmDires;
    }




}


