package com.teknei.sitm.gsab.entities;
// Generated 23/06/2015 11:21:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CoacScre generated by hbm2java
 */
public class CoacScre  implements java.io.Serializable {


     private int idScre;
     private CctmCata cctmCataByIdTipo;
     private CctmCata cctmCataByIdEsta;
     private CoacTcre coacTcre;
     private String codScre;
     private String desScre;
     private String usrCrea;
     private Date fchCrea;
     private String usrModi;
     private Date fchModi;
     private Set<CaupUsuaPref> caupUsuaPrefs = new HashSet<CaupUsuaPref>(0);

    public CoacScre() {
    }

	
    public CoacScre(int idScre, CctmCata cctmCataByIdTipo, CctmCata cctmCataByIdEsta, CoacTcre coacTcre, String codScre, String desScre, String usrCrea, Date fchCrea) {
        this.idScre = idScre;
        this.cctmCataByIdTipo = cctmCataByIdTipo;
        this.cctmCataByIdEsta = cctmCataByIdEsta;
        this.coacTcre = coacTcre;
        this.codScre = codScre;
        this.desScre = desScre;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
    }
    public CoacScre(int idScre, CctmCata cctmCataByIdTipo, CctmCata cctmCataByIdEsta, CoacTcre coacTcre, String codScre, String desScre, String usrCrea, Date fchCrea, String usrModi, Date fchModi, Set<CaupUsuaPref> caupUsuaPrefs) {
       this.idScre = idScre;
       this.cctmCataByIdTipo = cctmCataByIdTipo;
       this.cctmCataByIdEsta = cctmCataByIdEsta;
       this.coacTcre = coacTcre;
       this.codScre = codScre;
       this.desScre = desScre;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.usrModi = usrModi;
       this.fchModi = fchModi;
       this.caupUsuaPrefs = caupUsuaPrefs;
    }
   
    public int getIdScre() {
        return this.idScre;
    }
    
    public void setIdScre(int idScre) {
        this.idScre = idScre;
    }
    public CctmCata getCctmCataByIdTipo() {
        return this.cctmCataByIdTipo;
    }
    
    public void setCctmCataByIdTipo(CctmCata cctmCataByIdTipo) {
        this.cctmCataByIdTipo = cctmCataByIdTipo;
    }
    public CctmCata getCctmCataByIdEsta() {
        return this.cctmCataByIdEsta;
    }
    
    public void setCctmCataByIdEsta(CctmCata cctmCataByIdEsta) {
        this.cctmCataByIdEsta = cctmCataByIdEsta;
    }
    public CoacTcre getCoacTcre() {
        return this.coacTcre;
    }
    
    public void setCoacTcre(CoacTcre coacTcre) {
        this.coacTcre = coacTcre;
    }
    public String getCodScre() {
        return this.codScre;
    }
    
    public void setCodScre(String codScre) {
        this.codScre = codScre;
    }
    public String getDesScre() {
        return this.desScre;
    }
    
    public void setDesScre(String desScre) {
        this.desScre = desScre;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public String getUsrModi() {
        return this.usrModi;
    }
    
    public void setUsrModi(String usrModi) {
        this.usrModi = usrModi;
    }
    public Date getFchModi() {
        return this.fchModi;
    }
    
    public void setFchModi(Date fchModi) {
        this.fchModi = fchModi;
    }
    public Set<CaupUsuaPref> getCaupUsuaPrefs() {
        return this.caupUsuaPrefs;
    }
    
    public void setCaupUsuaPrefs(Set<CaupUsuaPref> caupUsuaPrefs) {
        this.caupUsuaPrefs = caupUsuaPrefs;
    }




}


