package com.teknei.sitm.gsab.entities;
// Generated 23/06/2015 11:21:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CoacTcre generated by hbm2java
 */
public class CoacTcre  implements java.io.Serializable {


     private int idTcre;
     private CctmCata cctmCataByTipoCred;
     private CctmCata cctmCataByIdEsta;
     private CctmCata cctmCataByIdTipo;
     private String codTcre;
     private String desTcre;
     private String usrCrea;
     private Date fchCrea;
     private String usrModi;
     private Date fchModi;
     private Set<CoacScre> coacScres = new HashSet<CoacScre>(0);

    public CoacTcre() {
    }

	
    public CoacTcre(int idTcre, CctmCata cctmCataByTipoCred, CctmCata cctmCataByIdEsta, CctmCata cctmCataByIdTipo, String codTcre, String desTcre, String usrCrea, Date fchCrea) {
        this.idTcre = idTcre;
        this.cctmCataByTipoCred = cctmCataByTipoCred;
        this.cctmCataByIdEsta = cctmCataByIdEsta;
        this.cctmCataByIdTipo = cctmCataByIdTipo;
        this.codTcre = codTcre;
        this.desTcre = desTcre;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
    }
    public CoacTcre(int idTcre, CctmCata cctmCataByTipoCred, CctmCata cctmCataByIdEsta, CctmCata cctmCataByIdTipo, String codTcre, String desTcre, String usrCrea, Date fchCrea, String usrModi, Date fchModi, Set<CoacScre> coacScres) {
       this.idTcre = idTcre;
       this.cctmCataByTipoCred = cctmCataByTipoCred;
       this.cctmCataByIdEsta = cctmCataByIdEsta;
       this.cctmCataByIdTipo = cctmCataByIdTipo;
       this.codTcre = codTcre;
       this.desTcre = desTcre;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.usrModi = usrModi;
       this.fchModi = fchModi;
       this.coacScres = coacScres;
    }
   
    public int getIdTcre() {
        return this.idTcre;
    }
    
    public void setIdTcre(int idTcre) {
        this.idTcre = idTcre;
    }
    public CctmCata getCctmCataByTipoCred() {
        return this.cctmCataByTipoCred;
    }
    
    public void setCctmCataByTipoCred(CctmCata cctmCataByTipoCred) {
        this.cctmCataByTipoCred = cctmCataByTipoCred;
    }
    public CctmCata getCctmCataByIdEsta() {
        return this.cctmCataByIdEsta;
    }
    
    public void setCctmCataByIdEsta(CctmCata cctmCataByIdEsta) {
        this.cctmCataByIdEsta = cctmCataByIdEsta;
    }
    public CctmCata getCctmCataByIdTipo() {
        return this.cctmCataByIdTipo;
    }
    
    public void setCctmCataByIdTipo(CctmCata cctmCataByIdTipo) {
        this.cctmCataByIdTipo = cctmCataByIdTipo;
    }
    public String getCodTcre() {
        return this.codTcre;
    }
    
    public void setCodTcre(String codTcre) {
        this.codTcre = codTcre;
    }
    public String getDesTcre() {
        return this.desTcre;
    }
    
    public void setDesTcre(String desTcre) {
        this.desTcre = desTcre;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public String getUsrModi() {
        return this.usrModi;
    }
    
    public void setUsrModi(String usrModi) {
        this.usrModi = usrModi;
    }
    public Date getFchModi() {
        return this.fchModi;
    }
    
    public void setFchModi(Date fchModi) {
        this.fchModi = fchModi;
    }
    public Set<CoacScre> getCoacScres() {
        return this.coacScres;
    }
    
    public void setCoacScres(Set<CoacScre> coacScres) {
        this.coacScres = coacScres;
    }




}


