package com.teknei.sitm.gsab.entities;
// Generated 23/06/2015 11:21:34 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * GsabLogAccs generated by hbm2java
 */
public class GsabLogAccs  implements java.io.Serializable {


     private long idLogAccs;
     private String usrName;
     private short succ;
     private Date fchCrea;
     private String usrCrea;
     private String ip;

    public GsabLogAccs() {
    }

	
    public GsabLogAccs(long idLogAccs, String usrName, short succ, Date fchCrea, String usrCrea) {
        this.idLogAccs = idLogAccs;
        this.usrName = usrName;
        this.succ = succ;
        this.fchCrea = fchCrea;
        this.usrCrea = usrCrea;
    }
    public GsabLogAccs(long idLogAccs, String usrName, short succ, Date fchCrea, String usrCrea, String ip) {
       this.idLogAccs = idLogAccs;
       this.usrName = usrName;
       this.succ = succ;
       this.fchCrea = fchCrea;
       this.usrCrea = usrCrea;
       this.ip = ip;
    }
   
    public long getIdLogAccs() {
        return this.idLogAccs;
    }
    
    public void setIdLogAccs(long idLogAccs) {
        this.idLogAccs = idLogAccs;
    }
    public String getUsrName() {
        return this.usrName;
    }
    
    public void setUsrName(String usrName) {
        this.usrName = usrName;
    }
    public short getSucc() {
        return this.succ;
    }
    
    public void setSucc(short succ) {
        this.succ = succ;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }




}


