package com.teknei.sitm.gsab.entities;
// Generated 23/06/2015 11:21:34 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * GsabPermPerf generated by hbm2java
 */
public class GsabPermPerf  implements java.io.Serializable {


     private int idPermPerf;
     private GsabModOper gsabModOper;
     private GsabPerfAccs gsabPerfAccs;
     private GsabSmodOper gsabSmodOper;
     private int idEsta;
     private int idTipo;
     private String usrCrea;
     private Date fchCrea;
     private String usrModi;
     private Date fchModi;

    public GsabPermPerf() {
    }

	
    public GsabPermPerf(int idPermPerf, GsabModOper gsabModOper, GsabPerfAccs gsabPerfAccs, int idEsta, int idTipo, String usrCrea, Date fchCrea) {
        this.idPermPerf = idPermPerf;
        this.gsabModOper = gsabModOper;
        this.gsabPerfAccs = gsabPerfAccs;
        this.idEsta = idEsta;
        this.idTipo = idTipo;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
    }
    public GsabPermPerf(int idPermPerf, GsabModOper gsabModOper, GsabPerfAccs gsabPerfAccs, GsabSmodOper gsabSmodOper, int idEsta, int idTipo, String usrCrea, Date fchCrea, String usrModi, Date fchModi) {
       this.idPermPerf = idPermPerf;
       this.gsabModOper = gsabModOper;
       this.gsabPerfAccs = gsabPerfAccs;
       this.gsabSmodOper = gsabSmodOper;
       this.idEsta = idEsta;
       this.idTipo = idTipo;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.usrModi = usrModi;
       this.fchModi = fchModi;
    }
   
    public int getIdPermPerf() {
        return this.idPermPerf;
    }
    
    public void setIdPermPerf(int idPermPerf) {
        this.idPermPerf = idPermPerf;
    }
    public GsabModOper getGsabModOper() {
        return this.gsabModOper;
    }
    
    public void setGsabModOper(GsabModOper gsabModOper) {
        this.gsabModOper = gsabModOper;
    }
    public GsabPerfAccs getGsabPerfAccs() {
        return this.gsabPerfAccs;
    }
    
    public void setGsabPerfAccs(GsabPerfAccs gsabPerfAccs) {
        this.gsabPerfAccs = gsabPerfAccs;
    }
    public GsabSmodOper getGsabSmodOper() {
        return this.gsabSmodOper;
    }
    
    public void setGsabSmodOper(GsabSmodOper gsabSmodOper) {
        this.gsabSmodOper = gsabSmodOper;
    }
    public int getIdEsta() {
        return this.idEsta;
    }
    
    public void setIdEsta(int idEsta) {
        this.idEsta = idEsta;
    }
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public String getUsrModi() {
        return this.usrModi;
    }
    
    public void setUsrModi(String usrModi) {
        this.usrModi = usrModi;
    }
    public Date getFchModi() {
        return this.fchModi;
    }
    
    public void setFchModi(Date fchModi) {
        this.fchModi = fchModi;
    }




}


