package com.teknei.sitm.gsab.entities;
// Generated 23/06/2015 11:21:34 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * GsabUsrPerf generated by hbm2java
 */
public class GsabUsrPerf  implements java.io.Serializable {


     private int idUsrPerf;
     private GsabPerfAccs gsabPerfAccs;
     private int idPerfAccs;
     private String usrName;
     private int idEsta;
     private int idTipo;
     private String usrCrea;
     private Date fchCrea;
     private String usrModi;
     private Date fchModi;

    public GsabUsrPerf() {
    }

	
    public GsabUsrPerf(GsabPerfAccs gsabPerfAccs, int idPerfAccs, String usrName, int idEsta, int idTipo, String usrCrea, Date fchCrea) {
        this.gsabPerfAccs = gsabPerfAccs;
        this.idPerfAccs = idPerfAccs;
        this.usrName = usrName;
        this.idEsta = idEsta;
        this.idTipo = idTipo;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
    }
    public GsabUsrPerf(GsabPerfAccs gsabPerfAccs, int idPerfAccs, String usrName, int idEsta, int idTipo, String usrCrea, Date fchCrea, String usrModi, Date fchModi) {
       this.gsabPerfAccs = gsabPerfAccs;
       this.idPerfAccs = idPerfAccs;
       this.usrName = usrName;
       this.idEsta = idEsta;
       this.idTipo = idTipo;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.usrModi = usrModi;
       this.fchModi = fchModi;
    }
   
    public int getIdUsrPerf() {
        return this.idUsrPerf;
    }
    
    public void setIdUsrPerf(int idUsrPerf) {
        this.idUsrPerf = idUsrPerf;
    }
    public GsabPerfAccs getGsabPerfAccs() {
        return this.gsabPerfAccs;
    }
    
    public void setGsabPerfAccs(GsabPerfAccs gsabPerfAccs) {
        this.gsabPerfAccs = gsabPerfAccs;
    }
    public int getIdPerfAccs() {
        return this.idPerfAccs;
    }
    
    public void setIdPerfAccs(int idPerfAccs) {
        this.idPerfAccs = idPerfAccs;
    }
    public String getUsrName() {
        return this.usrName;
    }
    
    public void setUsrName(String usrName) {
        this.usrName = usrName;
    }
    public int getIdEsta() {
        return this.idEsta;
    }
    
    public void setIdEsta(int idEsta) {
        this.idEsta = idEsta;
    }
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public String getUsrModi() {
        return this.usrModi;
    }
    
    public void setUsrModi(String usrModi) {
        this.usrModi = usrModi;
    }
    public Date getFchModi() {
        return this.fchModi;
    }
    
    public void setFchModi(Date fchModi) {
        this.fchModi = fchModi;
    }




}


