package com.teknei.sitm.gsab.entities;
// Generated 23/06/2015 11:21:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * GsabSmodOper generated by hbm2java
 */
public class GsabSmodOper  implements java.io.Serializable {


     private int idSmodOper;
     private String nomSmodOper;
     private String desSmodOper;
     private int numOrdn;
     private int idEsta;
     private int idTipo;
     private String usrCrea;
     private Date fchCrea;
     private String usrModi;
     private Date fchModi;
     private Set<GsabLogOper> gsabLogOpers = new HashSet<GsabLogOper>(0);
     private Set<GsabPermPerf> gsabPermPerfs = new HashSet<GsabPermPerf>(0);

    public GsabSmodOper() {
    }

	
    public GsabSmodOper(int idSmodOper, String nomSmodOper, int numOrdn, int idEsta, int idTipo, String usrCrea, Date fchCrea) {
        this.idSmodOper = idSmodOper;
        this.nomSmodOper = nomSmodOper;
        this.numOrdn = numOrdn;
        this.idEsta = idEsta;
        this.idTipo = idTipo;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
    }
    public GsabSmodOper(int idSmodOper, String nomSmodOper, String desSmodOper, int numOrdn, int idEsta, int idTipo, String usrCrea, Date fchCrea, String usrModi, Date fchModi, Set<GsabLogOper> gsabLogOpers, Set<GsabPermPerf> gsabPermPerfs) {
       this.idSmodOper = idSmodOper;
       this.nomSmodOper = nomSmodOper;
       this.desSmodOper = desSmodOper;
       this.numOrdn = numOrdn;
       this.idEsta = idEsta;
       this.idTipo = idTipo;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.usrModi = usrModi;
       this.fchModi = fchModi;
       this.gsabLogOpers = gsabLogOpers;
       this.gsabPermPerfs = gsabPermPerfs;
    }
   
    public int getIdSmodOper() {
        return this.idSmodOper;
    }
    
    public void setIdSmodOper(int idSmodOper) {
        this.idSmodOper = idSmodOper;
    }
    public String getNomSmodOper() {
        return this.nomSmodOper;
    }
    
    public void setNomSmodOper(String nomSmodOper) {
        this.nomSmodOper = nomSmodOper;
    }
    public String getDesSmodOper() {
        return this.desSmodOper;
    }
    
    public void setDesSmodOper(String desSmodOper) {
        this.desSmodOper = desSmodOper;
    }
    public int getNumOrdn() {
        return this.numOrdn;
    }
    
    public void setNumOrdn(int numOrdn) {
        this.numOrdn = numOrdn;
    }
    public int getIdEsta() {
        return this.idEsta;
    }
    
    public void setIdEsta(int idEsta) {
        this.idEsta = idEsta;
    }
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public String getUsrModi() {
        return this.usrModi;
    }
    
    public void setUsrModi(String usrModi) {
        this.usrModi = usrModi;
    }
    public Date getFchModi() {
        return this.fchModi;
    }
    
    public void setFchModi(Date fchModi) {
        this.fchModi = fchModi;
    }
    public Set<GsabLogOper> getGsabLogOpers() {
        return this.gsabLogOpers;
    }
    
    public void setGsabLogOpers(Set<GsabLogOper> gsabLogOpers) {
        this.gsabLogOpers = gsabLogOpers;
    }
    public Set<GsabPermPerf> getGsabPermPerfs() {
        return this.gsabPermPerfs;
    }
    
    public void setGsabPermPerfs(Set<GsabPermPerf> gsabPermPerfs) {
        this.gsabPermPerfs = gsabPermPerfs;
    }




}


