package com.teknei.sitm.gsab.entities;
// Generated 23/06/2015 11:21:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * GsabPerfAccs generated by hbm2java
 */
public class GsabPerfAccs  implements java.io.Serializable {


     private int idPerfAccs;
     private String nomPerfAccs;
     private int idEsta;
     private int idTipo;
     private String usrCrea;
     private Date fchCrea;
     private String usrModi;
     private Date fchModi;
     private Set<GsabPermPerf> gsabPermPerfs = new HashSet<GsabPermPerf>(0);
     private GsabUsrPerf gsabUsrPerf;

    public GsabPerfAccs() {
    }

	
    public GsabPerfAccs(int idPerfAccs, String nomPerfAccs, int idEsta, int idTipo, String usrCrea, Date fchCrea) {
        this.idPerfAccs = idPerfAccs;
        this.nomPerfAccs = nomPerfAccs;
        this.idEsta = idEsta;
        this.idTipo = idTipo;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
    }
    public GsabPerfAccs(int idPerfAccs, String nomPerfAccs, int idEsta, int idTipo, String usrCrea, Date fchCrea, String usrModi, Date fchModi, Set<GsabPermPerf> gsabPermPerfs, GsabUsrPerf gsabUsrPerf) {
       this.idPerfAccs = idPerfAccs;
       this.nomPerfAccs = nomPerfAccs;
       this.idEsta = idEsta;
       this.idTipo = idTipo;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.usrModi = usrModi;
       this.fchModi = fchModi;
       this.gsabPermPerfs = gsabPermPerfs;
       this.gsabUsrPerf = gsabUsrPerf;
    }
   
    public int getIdPerfAccs() {
        return this.idPerfAccs;
    }
    
    public void setIdPerfAccs(int idPerfAccs) {
        this.idPerfAccs = idPerfAccs;
    }
    public String getNomPerfAccs() {
        return this.nomPerfAccs;
    }
    
    public void setNomPerfAccs(String nomPerfAccs) {
        this.nomPerfAccs = nomPerfAccs;
    }
    public int getIdEsta() {
        return this.idEsta;
    }
    
    public void setIdEsta(int idEsta) {
        this.idEsta = idEsta;
    }
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public String getUsrModi() {
        return this.usrModi;
    }
    
    public void setUsrModi(String usrModi) {
        this.usrModi = usrModi;
    }
    public Date getFchModi() {
        return this.fchModi;
    }
    
    public void setFchModi(Date fchModi) {
        this.fchModi = fchModi;
    }
    public Set<GsabPermPerf> getGsabPermPerfs() {
        return this.gsabPermPerfs;
    }
    
    public void setGsabPermPerfs(Set<GsabPermPerf> gsabPermPerfs) {
        this.gsabPermPerfs = gsabPermPerfs;
    }
    public GsabUsrPerf getGsabUsrPerf() {
        return this.gsabUsrPerf;
    }
    
    public void setGsabUsrPerf(GsabUsrPerf gsabUsrPerf) {
        this.gsabUsrPerf = gsabUsrPerf;
    }




}


