package com.teknei.sitm.gsab.entities;
// Generated 23/06/2015 11:21:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SbeqEqui generated by hbm2java
 */
public class SbeqEqui  implements java.io.Serializable {


     private int idEqui;
     private CctmCata cctmCataByIdMod;
     private CctmCata cctmCataByIdTipo;
     private CctmCata cctmCataByIdEsta;
     private CctmCata cctmCataByIdEdoEqui;
     private int idInv;
     private String dirIp;
     private Date fchAlta;
     private String usrCrea;
     private Date fchCrea;
     private String usrModi;
     private Date fchModi;
     private Integer noAfil;
     private Integer idLinEst;
     private Integer idSuc;
     private Integer idVehi;
     private String noEcon;
     private String numeSeri;
     private Integer idConSis;
     private Set<SbopTurn> sbopTurns = new HashSet<SbopTurn>(0);
     private Set<CaupCeopConfEqui> caupCeopConfEquis = new HashSet<CaupCeopConfEqui>(0);

    public SbeqEqui() {
    }

	
    public SbeqEqui(int idEqui, CctmCata cctmCataByIdTipo, CctmCata cctmCataByIdEsta, CctmCata cctmCataByIdEdoEqui, int idInv, String dirIp, Date fchAlta, String usrCrea, Date fchCrea) {
        this.idEqui = idEqui;
        this.cctmCataByIdTipo = cctmCataByIdTipo;
        this.cctmCataByIdEsta = cctmCataByIdEsta;
        this.cctmCataByIdEdoEqui = cctmCataByIdEdoEqui;
        this.idInv = idInv;
        this.dirIp = dirIp;
        this.fchAlta = fchAlta;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
    }
    public SbeqEqui(int idEqui, CctmCata cctmCataByIdMod, CctmCata cctmCataByIdTipo, CctmCata cctmCataByIdEsta, CctmCata cctmCataByIdEdoEqui, int idInv, String dirIp, Date fchAlta, String usrCrea, Date fchCrea, String usrModi, Date fchModi, Integer noAfil, Integer idLinEst, Integer idSuc, Integer idVehi, String noEcon, String numeSeri, Integer idConSis, Set<SbopTurn> sbopTurns, Set<CaupCeopConfEqui> caupCeopConfEquis) {
       this.idEqui = idEqui;
       this.cctmCataByIdMod = cctmCataByIdMod;
       this.cctmCataByIdTipo = cctmCataByIdTipo;
       this.cctmCataByIdEsta = cctmCataByIdEsta;
       this.cctmCataByIdEdoEqui = cctmCataByIdEdoEqui;
       this.idInv = idInv;
       this.dirIp = dirIp;
       this.fchAlta = fchAlta;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.usrModi = usrModi;
       this.fchModi = fchModi;
       this.noAfil = noAfil;
       this.idLinEst = idLinEst;
       this.idSuc = idSuc;
       this.idVehi = idVehi;
       this.noEcon = noEcon;
       this.numeSeri = numeSeri;
       this.idConSis = idConSis;
       this.sbopTurns = sbopTurns;
       this.caupCeopConfEquis = caupCeopConfEquis;
    }
   
    public int getIdEqui() {
        return this.idEqui;
    }
    
    public void setIdEqui(int idEqui) {
        this.idEqui = idEqui;
    }
    public CctmCata getCctmCataByIdMod() {
        return this.cctmCataByIdMod;
    }
    
    public void setCctmCataByIdMod(CctmCata cctmCataByIdMod) {
        this.cctmCataByIdMod = cctmCataByIdMod;
    }
    public CctmCata getCctmCataByIdTipo() {
        return this.cctmCataByIdTipo;
    }
    
    public void setCctmCataByIdTipo(CctmCata cctmCataByIdTipo) {
        this.cctmCataByIdTipo = cctmCataByIdTipo;
    }
    public CctmCata getCctmCataByIdEsta() {
        return this.cctmCataByIdEsta;
    }
    
    public void setCctmCataByIdEsta(CctmCata cctmCataByIdEsta) {
        this.cctmCataByIdEsta = cctmCataByIdEsta;
    }
    public CctmCata getCctmCataByIdEdoEqui() {
        return this.cctmCataByIdEdoEqui;
    }
    
    public void setCctmCataByIdEdoEqui(CctmCata cctmCataByIdEdoEqui) {
        this.cctmCataByIdEdoEqui = cctmCataByIdEdoEqui;
    }
    public int getIdInv() {
        return this.idInv;
    }
    
    public void setIdInv(int idInv) {
        this.idInv = idInv;
    }
    public String getDirIp() {
        return this.dirIp;
    }
    
    public void setDirIp(String dirIp) {
        this.dirIp = dirIp;
    }
    public Date getFchAlta() {
        return this.fchAlta;
    }
    
    public void setFchAlta(Date fchAlta) {
        this.fchAlta = fchAlta;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public String getUsrModi() {
        return this.usrModi;
    }
    
    public void setUsrModi(String usrModi) {
        this.usrModi = usrModi;
    }
    public Date getFchModi() {
        return this.fchModi;
    }
    
    public void setFchModi(Date fchModi) {
        this.fchModi = fchModi;
    }
    public Integer getNoAfil() {
        return this.noAfil;
    }
    
    public void setNoAfil(Integer noAfil) {
        this.noAfil = noAfil;
    }
    public Integer getIdLinEst() {
        return this.idLinEst;
    }
    
    public void setIdLinEst(Integer idLinEst) {
        this.idLinEst = idLinEst;
    }
    public Integer getIdSuc() {
        return this.idSuc;
    }
    
    public void setIdSuc(Integer idSuc) {
        this.idSuc = idSuc;
    }
    public Integer getIdVehi() {
        return this.idVehi;
    }
    
    public void setIdVehi(Integer idVehi) {
        this.idVehi = idVehi;
    }
    public String getNoEcon() {
        return this.noEcon;
    }
    
    public void setNoEcon(String noEcon) {
        this.noEcon = noEcon;
    }
    public String getNumeSeri() {
        return this.numeSeri;
    }
    
    public void setNumeSeri(String numeSeri) {
        this.numeSeri = numeSeri;
    }
    public Integer getIdConSis() {
        return this.idConSis;
    }
    
    public void setIdConSis(Integer idConSis) {
        this.idConSis = idConSis;
    }
    public Set<SbopTurn> getSbopTurns() {
        return this.sbopTurns;
    }
    
    public void setSbopTurns(Set<SbopTurn> sbopTurns) {
        this.sbopTurns = sbopTurns;
    }
    public Set<CaupCeopConfEqui> getCaupCeopConfEquis() {
        return this.caupCeopConfEquis;
    }
    
    public void setCaupCeopConfEquis(Set<CaupCeopConfEqui> caupCeopConfEquis) {
        this.caupCeopConfEquis = caupCeopConfEquis;
    }




}


