package com.teknei.sitm.gsab.entities;
// Generated 23/06/2015 11:21:34 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SbopAsgnTurn generated by hbm2java
 */
public class SbopAsgnTurn  implements java.io.Serializable {


     private SbopAsgnTurnId id;
     private CctmCata cctmCataByIdTipo;
     private CctmCata cctmCataByIdEsta;
     private SbopTurn sbopTurn;
     private Integer idLinEst;
     private Integer idSuc;
     private Integer idVehi;
     private String noEcon;
     private String usrCrea;
     private Date fchCrea;
     private String usrModi;
     private Date fchModi;
     private Integer idConSis;

    public SbopAsgnTurn() {
    }

	
    public SbopAsgnTurn(SbopAsgnTurnId id, CctmCata cctmCataByIdTipo, CctmCata cctmCataByIdEsta, SbopTurn sbopTurn, String usrCrea, Date fchCrea) {
        this.id = id;
        this.cctmCataByIdTipo = cctmCataByIdTipo;
        this.cctmCataByIdEsta = cctmCataByIdEsta;
        this.sbopTurn = sbopTurn;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
    }
    public SbopAsgnTurn(SbopAsgnTurnId id, CctmCata cctmCataByIdTipo, CctmCata cctmCataByIdEsta, SbopTurn sbopTurn, Integer idLinEst, Integer idSuc, Integer idVehi, String noEcon, String usrCrea, Date fchCrea, String usrModi, Date fchModi, Integer idConSis) {
       this.id = id;
       this.cctmCataByIdTipo = cctmCataByIdTipo;
       this.cctmCataByIdEsta = cctmCataByIdEsta;
       this.sbopTurn = sbopTurn;
       this.idLinEst = idLinEst;
       this.idSuc = idSuc;
       this.idVehi = idVehi;
       this.noEcon = noEcon;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.usrModi = usrModi;
       this.fchModi = fchModi;
       this.idConSis = idConSis;
    }
   
    public SbopAsgnTurnId getId() {
        return this.id;
    }
    
    public void setId(SbopAsgnTurnId id) {
        this.id = id;
    }
    public CctmCata getCctmCataByIdTipo() {
        return this.cctmCataByIdTipo;
    }
    
    public void setCctmCataByIdTipo(CctmCata cctmCataByIdTipo) {
        this.cctmCataByIdTipo = cctmCataByIdTipo;
    }
    public CctmCata getCctmCataByIdEsta() {
        return this.cctmCataByIdEsta;
    }
    
    public void setCctmCataByIdEsta(CctmCata cctmCataByIdEsta) {
        this.cctmCataByIdEsta = cctmCataByIdEsta;
    }
    public SbopTurn getSbopTurn() {
        return this.sbopTurn;
    }
    
    public void setSbopTurn(SbopTurn sbopTurn) {
        this.sbopTurn = sbopTurn;
    }
    public Integer getIdLinEst() {
        return this.idLinEst;
    }
    
    public void setIdLinEst(Integer idLinEst) {
        this.idLinEst = idLinEst;
    }
    public Integer getIdSuc() {
        return this.idSuc;
    }
    
    public void setIdSuc(Integer idSuc) {
        this.idSuc = idSuc;
    }
    public Integer getIdVehi() {
        return this.idVehi;
    }
    
    public void setIdVehi(Integer idVehi) {
        this.idVehi = idVehi;
    }
    public String getNoEcon() {
        return this.noEcon;
    }
    
    public void setNoEcon(String noEcon) {
        this.noEcon = noEcon;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public String getUsrModi() {
        return this.usrModi;
    }
    
    public void setUsrModi(String usrModi) {
        this.usrModi = usrModi;
    }
    public Date getFchModi() {
        return this.fchModi;
    }
    
    public void setFchModi(Date fchModi) {
        this.fchModi = fchModi;
    }
    public Integer getIdConSis() {
        return this.idConSis;
    }
    
    public void setIdConSis(Integer idConSis) {
        this.idConSis = idConSis;
    }




}


