package com.teknei.sitm.gsab.entities;
// Generated 23/06/2015 11:21:34 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SbopTurn generated by hbm2java
 */
public class SbopTurn  implements java.io.Serializable {


     private SbopTurnId id;
     private CctmCata cctmCataByIdTipo;
     private CctmCata cctmCataByIdEdoSes;
     private CctmCata cctmCataByIdEsta;
     private SbeqEqui sbeqEqui;
     private SbopTarj sbopTarj;
     private Integer tarjVend;
     private BigDecimal montTurn;
     private Integer tarjExis;
     private Integer montCanc;
     private String usrCrea;
     private Date fchCrea;
     private String usrModi;
     private Date fchModi;
     private Date fchIniTurn;
     private Date fchFinTurn;
     private String uidTarj;
     private Integer idConSis;
     private Set<SbopAsgnTurn> sbopAsgnTurns = new HashSet<SbopAsgnTurn>(0);
     private Set<SbopTran> sbopTrans = new HashSet<SbopTran>(0);

    public SbopTurn() {
    }

	
    public SbopTurn(SbopTurnId id, CctmCata cctmCataByIdTipo, CctmCata cctmCataByIdEsta, SbeqEqui sbeqEqui, String usrCrea, Date fchCrea) {
        this.id = id;
        this.cctmCataByIdTipo = cctmCataByIdTipo;
        this.cctmCataByIdEsta = cctmCataByIdEsta;
        this.sbeqEqui = sbeqEqui;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
    }
    public SbopTurn(SbopTurnId id, CctmCata cctmCataByIdTipo, CctmCata cctmCataByIdEdoSes, CctmCata cctmCataByIdEsta, SbeqEqui sbeqEqui, SbopTarj sbopTarj, Integer tarjVend, BigDecimal montTurn, Integer tarjExis, Integer montCanc, String usrCrea, Date fchCrea, String usrModi, Date fchModi, Date fchIniTurn, Date fchFinTurn, String uidTarj, Integer idConSis, Set<SbopAsgnTurn> sbopAsgnTurns, Set<SbopTran> sbopTrans) {
       this.id = id;
       this.cctmCataByIdTipo = cctmCataByIdTipo;
       this.cctmCataByIdEdoSes = cctmCataByIdEdoSes;
       this.cctmCataByIdEsta = cctmCataByIdEsta;
       this.sbeqEqui = sbeqEqui;
       this.sbopTarj = sbopTarj;
       this.tarjVend = tarjVend;
       this.montTurn = montTurn;
       this.tarjExis = tarjExis;
       this.montCanc = montCanc;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.usrModi = usrModi;
       this.fchModi = fchModi;
       this.fchIniTurn = fchIniTurn;
       this.fchFinTurn = fchFinTurn;
       this.uidTarj = uidTarj;
       this.idConSis = idConSis;
       this.sbopAsgnTurns = sbopAsgnTurns;
       this.sbopTrans = sbopTrans;
    }
   
    public SbopTurnId getId() {
        return this.id;
    }
    
    public void setId(SbopTurnId id) {
        this.id = id;
    }
    public CctmCata getCctmCataByIdTipo() {
        return this.cctmCataByIdTipo;
    }
    
    public void setCctmCataByIdTipo(CctmCata cctmCataByIdTipo) {
        this.cctmCataByIdTipo = cctmCataByIdTipo;
    }
    public CctmCata getCctmCataByIdEdoSes() {
        return this.cctmCataByIdEdoSes;
    }
    
    public void setCctmCataByIdEdoSes(CctmCata cctmCataByIdEdoSes) {
        this.cctmCataByIdEdoSes = cctmCataByIdEdoSes;
    }
    public CctmCata getCctmCataByIdEsta() {
        return this.cctmCataByIdEsta;
    }
    
    public void setCctmCataByIdEsta(CctmCata cctmCataByIdEsta) {
        this.cctmCataByIdEsta = cctmCataByIdEsta;
    }
    public SbeqEqui getSbeqEqui() {
        return this.sbeqEqui;
    }
    
    public void setSbeqEqui(SbeqEqui sbeqEqui) {
        this.sbeqEqui = sbeqEqui;
    }
    public SbopTarj getSbopTarj() {
        return this.sbopTarj;
    }
    
    public void setSbopTarj(SbopTarj sbopTarj) {
        this.sbopTarj = sbopTarj;
    }
    public Integer getTarjVend() {
        return this.tarjVend;
    }
    
    public void setTarjVend(Integer tarjVend) {
        this.tarjVend = tarjVend;
    }
    public BigDecimal getMontTurn() {
        return this.montTurn;
    }
    
    public void setMontTurn(BigDecimal montTurn) {
        this.montTurn = montTurn;
    }
    public Integer getTarjExis() {
        return this.tarjExis;
    }
    
    public void setTarjExis(Integer tarjExis) {
        this.tarjExis = tarjExis;
    }
    public Integer getMontCanc() {
        return this.montCanc;
    }
    
    public void setMontCanc(Integer montCanc) {
        this.montCanc = montCanc;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public String getUsrModi() {
        return this.usrModi;
    }
    
    public void setUsrModi(String usrModi) {
        this.usrModi = usrModi;
    }
    public Date getFchModi() {
        return this.fchModi;
    }
    
    public void setFchModi(Date fchModi) {
        this.fchModi = fchModi;
    }
    public Date getFchIniTurn() {
        return this.fchIniTurn;
    }
    
    public void setFchIniTurn(Date fchIniTurn) {
        this.fchIniTurn = fchIniTurn;
    }
    public Date getFchFinTurn() {
        return this.fchFinTurn;
    }
    
    public void setFchFinTurn(Date fchFinTurn) {
        this.fchFinTurn = fchFinTurn;
    }
    public String getUidTarj() {
        return this.uidTarj;
    }
    
    public void setUidTarj(String uidTarj) {
        this.uidTarj = uidTarj;
    }
    public Integer getIdConSis() {
        return this.idConSis;
    }
    
    public void setIdConSis(Integer idConSis) {
        this.idConSis = idConSis;
    }
    public Set<SbopAsgnTurn> getSbopAsgnTurns() {
        return this.sbopAsgnTurns;
    }
    
    public void setSbopAsgnTurns(Set<SbopAsgnTurn> sbopAsgnTurns) {
        this.sbopAsgnTurns = sbopAsgnTurns;
    }
    public Set<SbopTran> getSbopTrans() {
        return this.sbopTrans;
    }
    
    public void setSbopTrans(Set<SbopTran> sbopTrans) {
        this.sbopTrans = sbopTrans;
    }




}


