package com.teknei.sitm.gsab.entities;
// Generated 23/06/2015 11:21:34 PM by Hibernate Tools 4.3.1



/**
 * SbopAsgnTurnId generated by hbm2java
 */
public class SbopAsgnTurnId  implements java.io.Serializable {


     private int idAsgnTurn;
     private int idTurn;
     private int idEqui;

    public SbopAsgnTurnId() {
    }

    public SbopAsgnTurnId(int idAsgnTurn, int idTurn, int idEqui) {
       this.idAsgnTurn = idAsgnTurn;
       this.idTurn = idTurn;
       this.idEqui = idEqui;
    }
   
    public int getIdAsgnTurn() {
        return this.idAsgnTurn;
    }
    
    public void setIdAsgnTurn(int idAsgnTurn) {
        this.idAsgnTurn = idAsgnTurn;
    }
    public int getIdTurn() {
        return this.idTurn;
    }
    
    public void setIdTurn(int idTurn) {
        this.idTurn = idTurn;
    }
    public int getIdEqui() {
        return this.idEqui;
    }
    
    public void setIdEqui(int idEqui) {
        this.idEqui = idEqui;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SbopAsgnTurnId) ) return false;
		 SbopAsgnTurnId castOther = ( SbopAsgnTurnId ) other; 
         
		 return (this.getIdAsgnTurn()==castOther.getIdAsgnTurn())
 && (this.getIdTurn()==castOther.getIdTurn())
 && (this.getIdEqui()==castOther.getIdEqui());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdAsgnTurn();
         result = 37 * result + this.getIdTurn();
         result = 37 * result + this.getIdEqui();
         return result;
   }   


}


