package com.teknei.sitm.gsab.entities;
// Generated 23/06/2015 11:21:34 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * SbopTran generated by hbm2java
 */
public class SbopTran  implements java.io.Serializable {


     private SbopTranId id;
     private CctmCata cctmCataByIdMotCanc;
     private CctmCata cctmCataByIdEmprTarj;
     private CctmCata cctmCataByIdTipo;
     private CctmCata cctmCataByIdEsta;
     private SbopTarj sbopTarj;
     private SbopTurn sbopTurn;
     private String uidTarj;
     private BigDecimal impoWeb;
     private Character canc;
     private BigDecimal montChcr;
     private char tipoTran;
     private Date fchTran;
     private String usrCrea;
     private Date fchCrea;
     private String usrModi;
     private Date fchModi;
     private Integer idLbla;
     private BigDecimal impoTran;
     private Integer idConSis;

    public SbopTran() {
    }

	
    public SbopTran(SbopTranId id, CctmCata cctmCataByIdTipo, CctmCata cctmCataByIdEsta, SbopTurn sbopTurn, char tipoTran, Date fchTran, String usrCrea, Date fchCrea) {
        this.id = id;
        this.cctmCataByIdTipo = cctmCataByIdTipo;
        this.cctmCataByIdEsta = cctmCataByIdEsta;
        this.sbopTurn = sbopTurn;
        this.tipoTran = tipoTran;
        this.fchTran = fchTran;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
    }
    public SbopTran(SbopTranId id, CctmCata cctmCataByIdMotCanc, CctmCata cctmCataByIdEmprTarj, CctmCata cctmCataByIdTipo, CctmCata cctmCataByIdEsta, SbopTarj sbopTarj, SbopTurn sbopTurn, String uidTarj, BigDecimal impoWeb, Character canc, BigDecimal montChcr, char tipoTran, Date fchTran, String usrCrea, Date fchCrea, String usrModi, Date fchModi, Integer idLbla, BigDecimal impoTran, Integer idConSis) {
       this.id = id;
       this.cctmCataByIdMotCanc = cctmCataByIdMotCanc;
       this.cctmCataByIdEmprTarj = cctmCataByIdEmprTarj;
       this.cctmCataByIdTipo = cctmCataByIdTipo;
       this.cctmCataByIdEsta = cctmCataByIdEsta;
       this.sbopTarj = sbopTarj;
       this.sbopTurn = sbopTurn;
       this.uidTarj = uidTarj;
       this.impoWeb = impoWeb;
       this.canc = canc;
       this.montChcr = montChcr;
       this.tipoTran = tipoTran;
       this.fchTran = fchTran;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.usrModi = usrModi;
       this.fchModi = fchModi;
       this.idLbla = idLbla;
       this.impoTran = impoTran;
       this.idConSis = idConSis;
    }
   
    public SbopTranId getId() {
        return this.id;
    }
    
    public void setId(SbopTranId id) {
        this.id = id;
    }
    public CctmCata getCctmCataByIdMotCanc() {
        return this.cctmCataByIdMotCanc;
    }
    
    public void setCctmCataByIdMotCanc(CctmCata cctmCataByIdMotCanc) {
        this.cctmCataByIdMotCanc = cctmCataByIdMotCanc;
    }
    public CctmCata getCctmCataByIdEmprTarj() {
        return this.cctmCataByIdEmprTarj;
    }
    
    public void setCctmCataByIdEmprTarj(CctmCata cctmCataByIdEmprTarj) {
        this.cctmCataByIdEmprTarj = cctmCataByIdEmprTarj;
    }
    public CctmCata getCctmCataByIdTipo() {
        return this.cctmCataByIdTipo;
    }
    
    public void setCctmCataByIdTipo(CctmCata cctmCataByIdTipo) {
        this.cctmCataByIdTipo = cctmCataByIdTipo;
    }
    public CctmCata getCctmCataByIdEsta() {
        return this.cctmCataByIdEsta;
    }
    
    public void setCctmCataByIdEsta(CctmCata cctmCataByIdEsta) {
        this.cctmCataByIdEsta = cctmCataByIdEsta;
    }
    public SbopTarj getSbopTarj() {
        return this.sbopTarj;
    }
    
    public void setSbopTarj(SbopTarj sbopTarj) {
        this.sbopTarj = sbopTarj;
    }
    public SbopTurn getSbopTurn() {
        return this.sbopTurn;
    }
    
    public void setSbopTurn(SbopTurn sbopTurn) {
        this.sbopTurn = sbopTurn;
    }
    public String getUidTarj() {
        return this.uidTarj;
    }
    
    public void setUidTarj(String uidTarj) {
        this.uidTarj = uidTarj;
    }
    public BigDecimal getImpoWeb() {
        return this.impoWeb;
    }
    
    public void setImpoWeb(BigDecimal impoWeb) {
        this.impoWeb = impoWeb;
    }
    public Character getCanc() {
        return this.canc;
    }
    
    public void setCanc(Character canc) {
        this.canc = canc;
    }
    public BigDecimal getMontChcr() {
        return this.montChcr;
    }
    
    public void setMontChcr(BigDecimal montChcr) {
        this.montChcr = montChcr;
    }
    public char getTipoTran() {
        return this.tipoTran;
    }
    
    public void setTipoTran(char tipoTran) {
        this.tipoTran = tipoTran;
    }
    public Date getFchTran() {
        return this.fchTran;
    }
    
    public void setFchTran(Date fchTran) {
        this.fchTran = fchTran;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public String getUsrModi() {
        return this.usrModi;
    }
    
    public void setUsrModi(String usrModi) {
        this.usrModi = usrModi;
    }
    public Date getFchModi() {
        return this.fchModi;
    }
    
    public void setFchModi(Date fchModi) {
        this.fchModi = fchModi;
    }
    public Integer getIdLbla() {
        return this.idLbla;
    }
    
    public void setIdLbla(Integer idLbla) {
        this.idLbla = idLbla;
    }
    public BigDecimal getImpoTran() {
        return this.impoTran;
    }
    
    public void setImpoTran(BigDecimal impoTran) {
        this.impoTran = impoTran;
    }
    public Integer getIdConSis() {
        return this.idConSis;
    }
    
    public void setIdConSis(Integer idConSis) {
        this.idConSis = idConSis;
    }




}


