package com.teknei.sitm.gsab.entities;
// Generated 23/06/2015 11:21:34 PM by Hibernate Tools 4.3.1



/**
 * SbopTranId generated by hbm2java
 */
public class SbopTranId  implements java.io.Serializable {


     private int idTran;
     private int idTurn;
     private int idEqui;

    public SbopTranId() {
    }

    public SbopTranId(int idTran, int idTurn, int idEqui) {
       this.idTran = idTran;
       this.idTurn = idTurn;
       this.idEqui = idEqui;
    }
   
    public int getIdTran() {
        return this.idTran;
    }
    
    public void setIdTran(int idTran) {
        this.idTran = idTran;
    }
    public int getIdTurn() {
        return this.idTurn;
    }
    
    public void setIdTurn(int idTurn) {
        this.idTurn = idTurn;
    }
    public int getIdEqui() {
        return this.idEqui;
    }
    
    public void setIdEqui(int idEqui) {
        this.idEqui = idEqui;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SbopTranId) ) return false;
		 SbopTranId castOther = ( SbopTranId ) other; 
         
		 return (this.getIdTran()==castOther.getIdTran())
 && (this.getIdTurn()==castOther.getIdTurn())
 && (this.getIdEqui()==castOther.getIdEqui());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdTran();
         result = 37 * result + this.getIdTurn();
         result = 37 * result + this.getIdEqui();
         return result;
   }   


}


